Mikubill/sd-webui-controlnet

- scripts/cldm.py
- scripts/controlnet.py
Thank you for your great extension. I have been using it 👍. 
This PR adds `low vram` option for users with low VRAM.
My code is based on the original ControlNet's low_vram option ([commit: 1e5c75a](https://github.com/lllyasviel/ControlNet/commit/1e5c75a5cfb45c3fc727a152238045fb51f5660a)).
Best regards,
> add lowvram option

- README.md
great job with this, I tested with the pose model mainly (the best one) 😁
<details>
<summary>posenet stuff: (Click to expand:)</summary>
</details>
> add minimum requirements

- scripts/controlnet.py
- Moved image to top
- Changed refresh button to match existing
- Relabeled "Open drawing canvas" button to be more accurate
> Some UI adjustments

- README.md
- annotator/uniformer/mmseg/datasets/custom.py
- install.py
`prettytable` was only really used by a function that was never called.
> Patch out prettytable requirement

- annotator/hed/__init__.py
- annotator/midas/api.py
- annotator/mlsd/__init__.py
- annotator/openpose/__init__.py
- annotator/uniformer/__init__.py
Reverts Mikubill/sd-webui-controlnet#102
> Revert "use relative path for download directory"

- scripts/controlnet.py
> Increase Annotator resolution to 2048

- scripts/controlnet.py
> Add height/width swap button

- install.py
- scripts/controlnet.py
> Supporting SVG graphics as input (drag/drop and select file)

- annotator/uniformer/mmseg/core/evaluation/metrics.py
> chore: fix typo in metrics.py

- scripts/controlnet.py
When processing in img2img batch, users cannot change tab. Otherwise, the error `AttributeError: 'numpy.ndarray' object has no attribute 'save'` pops out again.
Also, when processing in img2img inpaint for example, and then changing to the batch tab before the end of the sampling process, the detectmap image will not be included in the output regardless of whether `Do not append detectmap to output` is enabled or not.
Replaced `create_on_after_component` with a class `Img2ImgTabTracker` as I think it is a more appropriate tool for a stateful function.
This PR fixes these issues. I kept the class `Img2ImgTabTracker` in `controlnet.py` and resisted the urge to move it to i.e. `utils.py` because it will force users to completely restart the webui as opposed to reloading the gradio interface.
> fix issue with img2img batch when changing tab during sampling

- scripts/controlnet.py
- scripts/xyz_grid_support.py
- Model
- Guidance Strength
- Preprocessor
- stength to strength
> Add some items to X/Y/Z plot (2)

- annotator/leres/__init__.py
- annotator/leres/leres/Resnet.py
- annotator/leres/leres/Resnext_torch.py
- annotator/leres/leres/multi_depth_model_woauxi.py
- annotator/leres/leres/net_tools.py
- annotator/leres/leres/network_auxi.py
- annotator/leres/leres/utils.py
- scripts/controlnet.py
- scripts/processor.py
My python is very beginner level so please feel free to make edits.
Code taken from https://github.com/thygate/stable-diffusion-webui-depthmap-script/tree/main/scripts
**Source**
**Prompt**
husky dog, high quality, sharp focus, realistic, wooden deck
Negative prompt: low quality, comic, anime, 3d render
Steps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 3553380952, Size: 512x512, Model hash: c35782bad8, Model: realisticVisionV13_v13VAEIncluded, Denoising strength: 1, Mask blur: 4, ControlNet Enabled: True, ControlNet Module: depth_leres, ControlNet Model: control_depth-fp16 [400750f6], ControlNet Weight: 1
**MiDaS**
**LeReS**
I found LeReS manages to preserve more detail and make images more realistic as a result.
- GPU only for now, needs a CPU check added when loading the model
- …
> Add support for LeReS depth

- .gitignore
- scripts/controlnet.py
This one is about #149 
If user allow detectedmap autosaving, detected map will be saved in different folders(preprocessor's name).
> Detected map autosave

- scripts/controlnet.py
Added if (__name__ == '__main__'):  to the controlnet.py so it can be called from other scripts. It's needed for the further development of the api.
> Added if (__name__ == '__main__'): 

- scripts/controlnet.py
ControlNet should use cropped masked area now if "only masked" is selected
> "Only masked" fix

- scripts/api.py
If the api is called, Controlnet does not take effect. Please try to put api.py under sd-webui/scripts.
> Add 'hiresfix' and 'guidance_strength' for api

- annotator/leres/__init__.py
Fixes error when running without CUDA
> fix: use CUDA only if available for leres

- scripts/api.py
> Add an api to get cn models list

- scripts/controlnet.py
> fix: metadata in multi-cn (#307)

- scripts/controlnet.py
More than 1 model enabled:
1 model enabled:
A small UI change. The stacked accordions were very frustrating.
> Multiple models across tabs, not accordions

- scripts/controlnet.py
closes #182.
I hope this is the last fix PR I have to open for the batch detection code 😅
Feel free to edit the code if you see a simpler way to test whether we are in an img2img tab.
> proper is_img2img implementation

- scripts/controlnet.py
Temporary revert this PR to make API works
> Revert "proper is_img2img implementation"

- scripts/api.py
> Added detect API endpoint

- scripts/controlnet.py
It's basically the same thing as before but instead the `is_img2img` args have default values. I tested:
- using controlnet by the gradio interface, in batch and non-batch img2img mode along with txt2img. the modes I tested are depth+preprocessor and scribble
- calling the API at `/controlnet/txt2img` and `/controlnet/img2img` with these bodies:
<details><summary>json object</summary>
<p>
(arrows `<-` indicate non-default values from fastapi `localhost/docs`)
```json
{
"prompt": "",
"negative_prompt": "",
"controlnet_input_image": ["<base64 string here>"], // <-
"controlnet_mask": [],
"controlnet_module": "",
"controlnet_model": "",
"controlnet_weight": 1,
"controlnet_resize_mode": "Scale to Fit (Inner Fit)",
"controlnet_lowvram": false,
"controlnet_processor_res": 64, …
```
> is_img2img impl with respect to api

- scripts/controlnet.py
- allow use of absolute (old behavior) or relative paths (new feature) for in config (applies to models, configs, detection maps)  
since it allows either absolute or relative paths, there should be no regressions for old configs
- save detection map images relative to webui outdir if using relative paths  
- assign html element id to controlnet main element  
closes #324
btw, great job with the extension!
> allow relative paths

- scripts/xyz_grid_support.py
Bug fixing for issues with [openpose] and [scribble] not functioning.😅
> Bug fixing and code improvement.

- scripts/controlnet.py
I changed the position from which to read the parameters so that the correct PNG information can be embedded.
Also, the selector function in parse_remote_call has been replaced with the get_remote_call method. In addition, strict and force arguments have been added. If the force argument is True, it ignores the value of control_net_allow_script_control.
When the 'strict' argument is set to True, the function returns the default value when the attribute value is not a list and the index argument is not zero. In other words, the following two code snippets return the same result.
`enabled = self.get_remote_call(p, "control_net_enabled", enabled, idx, strict=True)`
```
if shared.opts.data.get("control_net_allow_script_control", False):
p_enabled = getattr(p, "control_net_enabled", None)
if …
```
> Changed the location from which to read values from p.

- scripts/xyz_grid_support.py
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#xyz-plot
Support for range specification with the same specification as WebUI has been added.
The following expressions all return the same result.
- [1, 5], [2, 4], [3, 3], [4, 2], [5, 1]
- [1-5(+1), 5-1(-1)]
- [1-5(+1), 5-1[5]]
- [1-5[5], 5-1[5]]
If the number of elements is different, the missing elements will be filled with the last element.
> Example 1
- [1, 5-1[5]]
- [1, 5], [1, 4], [1, 3], [1, 2], [1, 1]
> Example 2
- [1-3[3], 5-1[5]]
- [1, 5], [2, 4], [3, 3], [3, 2], [3, 1]
Such expressions are also possible.
- 1-3, [4-6[2], 6-4[3]], [7, 2], None, [8-10[3]]
- 1, 2, 3, [4, 6], [6, 5], [6, 4], [7, 2], None, [8, None], [9, None], [10, None]
> Support for specifying a range of numbers.

- scripts/controlnet.py
This PR fix the model cache, the previous code was removing all models from cache every time and had some references preventing the data from being removed from RAM/VRAM, also you don't need to move the model to cpu before removing it, because the data will be removed from VRAM anyway after calling the `gc.collect()` and `devices.torch_gc()` if you removed all references.
Now the models are cached like the sd models in auto1111, using a `OrderedDict` and working as a FIFO list, the first model cached will be the one removed to open space for the new model being cached.
When the sd model changes, all models are removed from cache like the previous code.
Related issue #375
> Fix model cache

- scripts/controlnet.py
This PR incrementally removes control net models from the model cache and generally makes the model caching logic more intuitive. This removes the least recently *loaded* model. This isn't quite as user-friendly as the least recently *used* model, but that would require a more involved change.
I changed the default model cache size to 1 as that now behaves sensibly and seems to be the most conservative choice.
I haven't tested it, but I also changed the cache clearing logic when the model is changed to try to incrementally free memory instead of dumping everything from VRAM to RAM and then clearing it.
The code in this PR, like the current code, craps out when the "none" model is chosen. This seems to Do The Right Thing, but it should probably be handled more elegantly. This PR doesn't …
> Make model cache logic more sensible.

- annotator/binary/__init__.py
- scripts/api.py
- scripts/controlnet.py
- scripts/processor.py
Added a binary to the preprocessor.
It is similar to the existing Scribble process, but allows to set a threshold.
If the threshold is set to 0 or 255, the threshold is automatically set using Otsu's method.
> Add binary preprocessor

- scripts/xyz_grid_support.py
I deleted the AxisOption class because it is unlikely that the clone attribute will be needed in the future.
Other minor fixes.
> Code cleanup.

- scripts/controlnet.py
> fix: sensible defaults for remote call units

- scripts/external_code.py
> fix: ignore kwargs

- scripts/api.py
- scripts/controlnet.py
- scripts/external_code.py
- scripts/global_state.py
Reverts Mikubill/sd-webui-controlnet#601
> Revert "Added  a new API call to get the preprocessor list"

- scripts/api.py
- scripts/controlnet.py
- scripts/external_code.py
- scripts/global_state.py
Credits to @mishafarms for the code in #601.
> add back preprocessor in api

- scripts/api.py
- scripts/controlnet.py
- scripts/external_code.py
- scripts/global_state.py
Reverts Mikubill/sd-webui-controlnet#613
> Revert "add back preprocessor in api"

- scripts/api.py
- scripts/controlnet.py
- scripts/external_code.py
- scripts/global_state.py
This is the re-submission of my last PR.
Michael
> Added a method to get the list of preprocessors

- scripts/controlnet.py
Fixed issue mentioned here: https://github.com/Mikubill/sd-webui-controlnet/commit/c9993fdb84946b09fd8449733bed94bebbd39ddc#commitcomment-108732617
> Fix resolution mismatch in inpaint

- README.md
a simple sanity check of the pull request workflow
> test can i commit

- README.md
- annotator/oneformer/detectron2/data/datasets/cityscapes.py
- annotator/oneformer/detectron2/data/datasets/coco.py
- annotator/oneformer/detectron2/data/detection_utils.py
- annotator/oneformer/detectron2/evaluation/coco_evaluation.py
- annotator/oneformer/detectron2/evaluation/fast_eval_api.py
- annotator/oneformer/detectron2/evaluation/rotated_coco_evaluation.py
- annotator/oneformer/detectron2/evaluation/sem_seg_evaluation.py
- annotator/oneformer/detectron2/structures/masks.py
- annotator/oneformer/detectron2/utils/video_visualizer.py
- annotator/oneformer/detectron2/utils/visualizer.py
- annotator/oneformer/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py
- annotator/oneformer/oneformer/demo/visualizer.py
- annotator/oneformer/oneformer/evaluation/coco_evaluator.py
- annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
- annotator/oneformer/oneformer/evaluation/instance_evaluation.py
- annotator/oneformer/pycocotools/__init__.py
- annotator/oneformer/pycocotools/coco.py
- annotator/oneformer/pycocotools/cocoeval.py
- annotator/oneformer/pycocotools/mask.py
- requirements.txt
> remove buggy pycocotools

- scripts/hook.py
This reverts commit 7781656f6c99d97de3d9f0684b7594eaf8795887.
> Revert "fix clip vision for adapter"

- scripts/api.py
Updated to be consistent with the webui preprocessor naming.
Typo note: t2ia_color_gird should be changed to t2ia_color_grid in the list of webui preprocessors.
> Update detect endpoint

- scripts/controlnet.py
make it so that users don't have to completely restart webui after updating.
> importlib reload

- scripts/controlnet.py
delaying reloading xyz until we get rid of cyclic dependency.
> dont import xyz

- scripts/controlnet.py
IIUC the preprocessors are never unloaded. This fixes that.
> unload preprocessors

- scripts/controlnet.py
- scripts/hook.py
we don't want to clear all callbacks on cn restore
> Fix script callbacks clear

- scripts/controlnet.py
see https://github.com/Mikubill/sd-webui-controlnet/pull/849#issuecomment-1511365509
> ui fix, shorten hints

- scripts/controlnet.py
My SAM extension has already supported ControlNet inpainting if this PR could be merged. However, I cannot find a way to control inpainting given the original codebase. Please merge this PR to main and as soon as you merge, I will be able to publish SAM's support for ControlNet inpainting.
> Support Control Inpainting by SAM Extension

- annotator/openpose/__init__.py
- annotator/openpose/body.py
- annotator/openpose/face.py
- annotator/openpose/hand.py
- annotator/uniformer/__init__.py
- annotator/uniformer/inference.py
- annotator/zoe/__init__.py
- scripts/hook.py
seems that this can fix almost all amd problems.
but pidinet still does not work. some operations in pidi just does not support amd.
> fix 90% amd problems

- scripts/controlnet.py
> `processor` reload order

- scripts/api.py
- scripts/controlnet.py
- scripts/external_code.py
- tests/external_code_api/script_args_test.py
- tests/web_api/txt2img_test.py
This is my draft of pixel perfect mode.
see also https://github.com/Mikubill/sd-webui-controlnet/issues/924
i think i can finish it today
> Pixel perfect (unfinished, do not merge!)

- scripts/controlnet.py
This reverts commit 0c7998ab05101bcb1ac426e41e11dda5f7e7d8a1.
> Revert "simpler fix (#841)"

- scripts/controlnet.py
now we use both methods to update the unit
ignore the line breaks caused buy my ide...
> using both methods to update

- annotator/hed/__init__.py
Change requested by an important anonymous user
> Change requested by an important anonymous user

- scripts/external_code.py
Reverts Mikubill/sd-webui-controlnet#1006
> Revert "Fixed issue where Nontype causes a crash"

- scripts/controlnet.py
- scripts/controlnet_version.py
> Fix no detectmap option ignored

- scripts/controlnet_version.py
- scripts/hook.py
> fix all t2i adapter problems

- scripts/controlnet.py
- scripts/controlnet_version.py
- scripts/external_code.py
> convert control mode

- annotator/manga_line/LICENSE
- annotator/manga_line/__init__.py
- scripts/global_state.py
- scripts/processor.py
Adding initial working Manga Line Extraction Processor from https://github.com/ljsabc/MangaLineExtraction_PyTorch as requested in https://github.com/Mikubill/sd-webui-controlnet/issues/1046
This will need a code review as I'm not 100% sure what I'm doing. I have however tested it in Automatic1111 and it works.
I was getting errors when trying to unload the model, so I have commented out that section for now, I'm not sure if it needs it or not.
Here are some examples of it in use:
Original:
Processed:
Result(Prompt: Woman, blue hair, blue eyes, hair bun, collared shirt):
Compared to the Lineart Anime Processor:
> Add Manga Line Extraction Processor

- scripts/controlnet_version.py
- scripts/processor.py
https://github.com/Mikubill/sd-webui-controlnet/issues/1098
> emergency temp fix

- annotator/leres/__init__.py
https://cloudstor.aarnet.edu.au not happy 😋
> cloudstor.aarnet.edu.au -> 429 Too Many Requests

- tests/utils.py
- tests/web_api/txt2img_test.py
> [Unittest] Add txt2img test with every preprocessors

- scripts/api.py
- scripts/controlnet_version.py
- scripts/external_code.py
Remove the deprecated inference API routes. Discussion: #1132
> Remove deprecated api

- annotator/clip/__init__.py
- annotator/util.py
- scripts/controlnet.py
- scripts/controlnet_version.py
- scripts/processor.py
Well I finally begin to face this problem
closes
https://github.com/Mikubill/sd-webui-controlnet/issues/1170
> Try to fix all ratio problems

- scripts/controlnet.py
- scripts/controlnet_version.py
closes #1199
possible we can just remove it entirely too.
> Equal height fix

- scripts/controlnet.py
- scripts/controlnet_version.py
- scripts/hook.py
This is the first step in supporting more models
this is already tested and can be merged whenever 
but will merge after extensive tests
> first step in supporting more models

- scripts/controlnet.py
- scripts/movie2movie.py
Adding elem_id to all the gradio component of controlnet, we have a extension which use jspath to grap the controlnet component value in DOM, need to set the elem_id otherwise every release will got different jspath.
> [fix]Adding elem_id to all the gradio component of controlnet

- scripts/controlnet_version.py
- scripts/hook.py
Reverts Mikubill/sd-webui-controlnet#1242
> Revert "fix high res fix"

- scripts/controlnet_version.py
- scripts/hook.py
Reverts Mikubill/sd-webui-controlnet#1243
> Revert "Revert "fix high res fix""

- scripts/controlnet.py
- scripts/controlnet_version.py
- scripts/hook.py
We will begin to use prompt marker to find out which instance is cond or ucond.
This will close https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/153 https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/191
> shift to context marker for cond-ucond

- scripts/movie2movie.py
Fixed an issue where the output video would be BGR instead of RGB when using m2m and setting a tile.
> Fix m2m bug

- scripts/external_code.py
External tools like Photoshop Plugin can build UI for preprocessor reference more friendly.
> add 'model_free' in module_detail

- scripts/movie2movie.py
Modified to accept not only video but also image input when using m2m script.
> Fix m2m script to allow use of reference only

- scripts/controlnet.py
> fix typo in controlnet.py

- scripts/controlnet.py
- scripts/global_state.py
- scripts/hook.py
- scripts/processor.py
inpaint_only is just a inpaint preprocessor but only change masked area
> add inpaint_only

- scripts/controlnet.py
Many methods in controlnet.Script do not access `self`. Change them to static method so that we know they do not depend on instance states.
> Convert methods that do not access member data to static method

- scripts/controlnet.py
- scripts/external_code.py
This PR adds `int_value` method on ResizeMode enum so that type conversion becomes less painful.
> :hammer: Add int_value on ResizeMode

- scripts/api.py
- scripts/controlnet.py
- scripts/controlnet_ui/controlnet_ui_group.py
- scripts/external_code.py
- scripts/global_state.py
- scripts/logging.py
- scripts/utils.py
Reverts Mikubill/sd-webui-controlnet#1537
Causing build failure.
> Revert "Logging migration"

- scripts/xyz_grid_support.py
Added support for control mode to xyz grid
> Added support for control mode to xyz grid

- scripts/controlnet.py
- scripts/controlnet_version.py
Reverts Mikubill/sd-webui-controlnet#1611
> Revert "fix high-res fix"

- style.css
https://github.com/huchenlei/sd-webui-openpose-editor/discussions/20.
The user reported that close icon of the modal is hard to find. Make the close icon bigger to address this problem.
> :art: Make modal close button bigger

- scripts/controlnet.py
- tests/web_api/txt2img_test.py
Reverts Mikubill/sd-webui-controlnet#1668
> Revert ":hammer: Refactor bound check for threshold and resolution"

- scripts/external_code.py
Reverts Mikubill/sd-webui-controlnet#1678
close https://github.com/lllyasviel/ControlNet/issues/447 https://github.com/Mikubill/sd-webui-controlnet/discussions/1682 https://github.com/Mikubill/sd-webui-controlnet/commit/784eadbba6600b3ecc2e3b07363895e42d6b3e8f#commitcomment-119412946 https://github.com/Mikubill/sd-webui-controlnet/commit/784eadbba6600b3ecc2e3b07363895e42d6b3e8f#commitcomment-119423589
> Revert "Add typecheck on script args"

- scripts/controlnet.py
> :loud_sound: add unit.module to bound check logs

- scripts/controlnet.py
- tests/cn_script/cn_script_test.py
This PR extract the resize mode pick logic out from `choose_input_image`.
This PR also adds some unittests for `choose_input_image`.
> :white_check_mark: Add test on choose_input_image

- scripts/controlnet.py
> :memo: Explain why guidance_end is set twice

- scripts/controlnet.py
- scripts/utils.py
- tests/cn_script/utils_test.py
I found that with the change to the master branch, there were some conflicts with the previous commit https://github.com/Mikubill/sd-webui-controlnet/pull/1416. I made some adjustments and recommitted this optimization.
> feat: significantly accelerates detectmap_proc performance

- scripts/global_state.py
Issue reported in https://github.com/Mikubill/sd-webui-controlnet/pull/893#issuecomment-1620500296
> :bug: Only scan dir if dir exists

- javascript/active_units.js
> :bug: Revert img2img inpaint change

- annotator/openpose/cv_ox_det.py
- annotator/openpose/wholebody.py
> :bug: Handle no detection case

- scripts/controlnet_ui/controlnet_ui_group.py
- scripts/controlnet_version.py
> shorter message

- javascript/active_units.js
Obviously 100ms is not enough for gradio to do all its work, and have front-end updated. This PR makes the delay 1s.
> Use longer delay

- javascript/hints.js
- scripts/controlnet_ui/preset.py
Reverts Mikubill/sd-webui-controlnet#1986
Breaking image upload.
> Revert "Add reset preset button"

- annotator/openpose/__init__.py
- scripts/api.py
- scripts/controlnet_ui/controlnet_ui_group.py
- tests/annotator_tests/openpose_tests/json_encode_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/discussions/2029. 
This PR makes the `detect` endpoint returns openpose JSON along with detected maps as response.
> Add openpose json to API response

- annotator/openpose/__init__.py
- scripts/api.py
- scripts/controlnet_ui/controlnet_ui_group.py
- tests/annotator_tests/openpose_tests/json_encode_test.py
This PR relands #2033 with fix on run annotator in ui group.
> Relands #2033

- javascript/openpose_editor.js
- scripts/controlnet_ui/modal.py
- style.css
> Fix openpose edit button style

- scripts/controlnet.py
Good to have for larger pipelines
> increase possible model cache size

- internal_controlnet/external_code.py
Reverts Mikubill/sd-webui-controlnet#2133
Broken Adetailer. See https://github.com/Mikubill/sd-webui-controlnet/issues/2200.
> Revert "Update external_code.py   fix for issue 2132 2111"

- annotator/clipvision/__init__.py
Fix Controlnet cannot support the -- use CPU parameter, built-in will still load cuda
> Fix the issue of not recognizing the use CPU mode

- patch_version.py
This PR adds an util script to help manage version.
> :hammer: Add patch version script

- .github/workflows/tests.yml
- tests/web_api/txt2img_test.py
Closes #2231.
This PR adds more tests coverage on multiple Control types.
> :white_check_mark: More tests on SDXL models

- annotator/openpose/body.py
- annotator/openpose/hand.py
> :hammer: fix deprecation warnings

- javascript/openpose_editor.js
Closes #2308.
This PR fixes 2 issues:
- Unable to upload JSON that was uploaded before.
- Clicking `close` will make upload JSON not working.
> :bug: Fix upload json

- .github/workflows/tests.yml
- scripts/controlnet_model_guess.py
- tests/web_api/txt2img_test.py
Closes #2333.
This PR makes the extension correctly detect SD15 ControlNet LoRA.
> :wrench: Detect ControlNet LoRA for SD15

- annotator/anime_face_segment/__init__.py
> Fix issues #2312 caused by capitalization

- scripts/controlmodel_ipadapter.py
Closes #2208.
According to user report, q can be half precision (float16) on M-series chips MacOS. This PR patches the dtype inconsistent issue.
> :bug: Fix dtype issue in IPAdapter for MacOS

- style.css
Closes #2332.
Before:
After fix:
> :bug: Fix upload json button style

- scripts/api.py
- tests/web_api/detect_test.py
fix detect api mode, invert cannot return image base64
> fix image invert detect

- scripts/controlnet.py
Closes #2148.
This PR adds a new option in ControlNet settings to allow user disable crop of input image when inpaint area is set to "Only masked".
When this option is selected, the image crop will still be active when user invokes upscale script, which also uses inpaint area = "Only maksed" to crop tiles off the input image.
> :wrench: Add option to bypass ControlNet input image crop

- annotator/openpose/animalpose.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2374.
> :bug: Use opencv for onnx model inference in animal openpose

- javascript/photopea.js
- scripts/controlnet.py
- scripts/controlnet_ui/controlnet_ui_group.py
Related to https://github.com/Mikubill/sd-webui-controlnet/issues/2384.
Give user option to disable photopea quick edit feature.
> :wrench: Add option to disable photopea quick edit

- scripts/enums.py
- tests/web_api/txt2img_test.py
> :bug: Fix hr_option parsing

- javascript/photopea.js
> :wrench: Add promptbox for first time external site visit

- javascript/openpose_editor.js
This PR delays check of openpose editor availability to first time when user clicks `edit`.
> :wrench: Delay openpose editor availability test

- scripts/controlnet_ui/controlnet_ui_group.py
Relates to https://github.com/Mikubill/sd-webui-controlnet/issues/2414.
This PR fixes potential gradio timing issue on callback execution order.
> :bug: Fix gradio timing issue

- install.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2401.
> :bug: Check is_installed on base package

- scripts/processor.py
https://github.com/Mikubill/sd-webui-controlnet/discussions/2400#discussioncomment-8022924
> :bug: Fixes path style

- scripts/processor.py
Reverts Mikubill/sd-webui-controlnet#2420
> Revert ":bug: Fixes path style"

- scripts/controlnet_ui/controlnet_ui_group.py
Closes #1921.
This PR adds the long requested feature to upload a precise mask on ControlNet input image. (White is inpaint area)
Note: currently mask only works for inpaint model. We will add support for mask on other models soon. The mask on other models will limit the effect of ControlNetUnit to the masked area.
> :sparkles: Allow mask upload

- scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2476.
> :bug: Fix inpaint mask dim

- annotator/clipvision/__init__.py
- annotator/lama/saicinpainting/training/losses/segmentation.py
- annotator/zoe/zoedepth/models/base_models/midas_repo/run.py
I have already closed the previous one(Address：https://github.com/Mikubill/sd-webui-controlnet/pull/2500/files ) and brought up a new one。
Follow your suggestion and change to devices.get_device_for("controlnet") method。
If you have already made changes, I will close this.   thank！！！
>  Apply a small patch(devices.get_device_for)

- annotator/clipvision/__init__.py
- annotator/lama/saicinpainting/training/losses/segmentation.py
- annotator/zoe/zoedepth/models/base_models/midas_repo/run.py
Reverts Mikubill/sd-webui-controlnet#2503.
Reason: Break AMD card users (#2506).
I am not very sure how to approach this as I do not own an AMD card. Maybe the change in lama/zoe are fine, but this needs further verification.
> Revert " Apply a small patch(devices.get_device_for)"

- install.py
- Fix the issue that handrefinerportable package installation is not corrected detected.
- Simplify install script.
- Allow custom wheel url to be recognized for insightface.
> :bug: Fix install script

- scripts/controlnet_ui/controlnet_ui_group.py
Closes #2516.
This PR makes compatibility effort to make new UI change work for A1111 1.6.0. Somehow all img2img tab components are not recognized in 1.6.0 A1111. This PR marks them as optional.
> :bug: backward compatible for A1111 1.6.0

- scripts/controlnet.py
- `high_res_fix` flag does not change within the loop
- Move inpaint module check out of input_image processing logic block
> :truck: Move statements

- annotator/clipvision/__init__.py
fix issue: [2553](https://github.com/Mikubill/sd-webui-controlnet/issues/2553)
> fix: removed the 'with' statement causing AttributeError: __enter__

- scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2554.
> :bug: Fix ControlLoRA

- annotator/clipvision/__init__.py
Closes #2558.
The issue was introduced by https://github.com/Mikubill/sd-webui-controlnet/pull/2556.
> :bug: Fix clip device

- internal_controlnet/external_code.py
- scripts/controlmodel_ipadapter.py
- scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2568.
Restore original ipadapter behaviour.
> :bug: Fix ip-adapter

- internal_controlnet/external_code.py
- scripts/controlmodel_ipadapter.py
- scripts/controlnet_ui/controlnet_ui_group.py
- scripts/processor.py
- tests/web_api/full_coverage/ipadapter_test.py
- tests/web_api/full_coverage/template.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2572.
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2557.
This PR allows all IP-Adapters accept multiple inputs, and do the injection in a single unit.
> ⚡ Real multi-inputs unit

- internal_controlnet/external_code.py
- scripts/controlmodel_ipadapter.py
- scripts/controlnet_ui/controlnet_ui_group.py
- scripts/processor.py
- tests/web_api/full_coverage/ipadapter_test.py
- tests/web_api/full_coverage/template.py
Reverts Mikubill/sd-webui-controlnet#2578
Revert reason: https://github.com/Mikubill/sd-webui-controlnet/issues/2581
> Revert "⚡ Real multi-inputs unit"

- scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2587.
> :bug: Fix txt2img send dimensions

- scripts/controlnet_ui/controlnet_ui_group.py
Relands #2595.
- More robust check on whether all units have been initialized yet.
- Register core local callbacks on render. If something break, core functionalities are preserved.
> Reland :bug: Disable checkpoint callback for SDNext

- scripts/controlnet_ui/controlnet_ui_group.py
> :bug: Fix model refresh

- scripts/controlnet_model_guess.py
Make error message cleaner when user falls into that branch. https://github.com/Mikubill/sd-webui-controlnet/issues/2573
> :bug: Correctly raise exception

- install.py
> Update hand refiner

- .github/workflows/lint.yaml
- .gitignore
- internal_controlnet/external_code.py
- pyproject.toml
Add ruff linter dependency. We will gradually fix existing lint issues and get directories down from exclude list.
> Add ruff linter dep

- pyproject.toml
- scripts/adapter.py
- scripts/api.py
- scripts/cldm.py
- scripts/controlmodel_ipadapter.py
- scripts/controlnet.py
- scripts/controlnet_diffusers.py
- scripts/controlnet_lllite.py
- scripts/controlnet_ui/controlnet_ui_group.py
- scripts/controlnet_ui/openpose_editor.py
- scripts/controlnet_ui/photopea.py
- scripts/controlnet_version.py
- scripts/external_code.py
- scripts/global_state.py
- scripts/hook.py
- scripts/processor.py
Fix many linter errors in under `/script`.
> Fix linter issues under `/script`

- scripts/hook.py
Adjust log level so users don't panic out.
> Adjust log level

- scripts/controlnet.py
> fix inpaint

- scripts/controlnet_version.py
> 📝 Update to version v1.1.441

- scripts/hook.py
> Fix crash on A1111 dev

- README.md
Wiki page for model download added. Update the outdated download section in README to point to wiki page.
> Update model download section

- scripts/controlnet.py
- scripts/controlnet_model_guess.py
- scripts/ipadapter/ipadapter_model.py
- scripts/ipadapter/plugable_ipadapter.py
Move some logic from `PlugableIPAdapter` to `IPAdapterModel`.
> Refactor ipadapter

- scripts/ipadapter/presets.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2711.
This PR adds 2 v11 ipadapter models to preset list.
> Add v11 ipadapter presets

- internal_controlnet/external_code.py
- scripts/processor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2726.
> Fix faceid

- scripts/processor.py
> Fix insightface BGR channel issue

- internal_controlnet/external_code.py
- scripts/api.py
- scripts/controlnet.py
- scripts/processor.py
- tests/cn_script/cn_script_test.py
- tests/web_api/detect_test.py
- tests/web_api/generation_test.py
- tests/web_api/template.py
Closes #2732.
This PR aligns the `controlnet/detect` API endpoint's behaviour on default processor_res/threshold_a/threshold_b with the behaviour on UI interface.
> Change API processor_res/threshold_a/threshold_b default values

- scripts/controlnet.py
> Do not check ip-adapter-auto when unit disabled

- internal_controlnet/external_code.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2771.
> Fix API parsing of ipadapter_input

- scripts/controlnet_ui/preset.py
> Fix control type infer in preset panel

- scripts/utils.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2795.
> Fix canny greyscale

- scripts/xyz_grid_support.py
Upstream change:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15532
> Fix xyz script module check

- internal_controlnet/external_code.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2812.
> Add warning on unrecognized param

- README.md
Update README for model release
> Update README for model release

- .github/workflows/tests.yml
This PR update A1111 test env from 1.6.0 to 1.9.3.
> Change test target to A1111 1.9.3

- scripts/preprocessor/model_free_preprocessors.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2833.
> Fix blur_gaussian slider param

- scripts/controlnet.py
https://github.com/Mikubill/sd-webui-controlnet/discussions/2589#discussioncomment-9315951
Need to refactor enum handling later.
> Quick fix enum issue

- internal_controlnet/args.py
> Add animatediff_batch flag on ControlNetUnit

- internal_controlnet/args.py
- unit_tests/args_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2870.
> Accept RGBA image as input

- internal_controlnet/args.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2876.
> Add more animatediff compatible fields

- scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2875.
> Restore unit state update listeners

- internal_controlnet/args.py
- scripts/controlnet.py
- scripts/preprocessor/pulid.py
- scripts/supported_preprocessor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2862.
Run `torch.cuda.empty_cache()` to clear gpu cache.
Refrence in original PuLID repo:
https://github.com/ToTheBeginning/PuLID/blob/7572f73de403187699075504e8415f9b00d98858/pulid/pipeline.py#L95-L96
> Fix PuLID VRAM leak

- annotator/teed/__init__.py
- scripts/preprocessor/__init__.py
- scripts/preprocessor/legacy/preprocessor_compiled.py
- scripts/preprocessor/legacy/processor.py
- scripts/preprocessor/teed.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2903.
This PR adds `softedge_anyline` preprocessor.
> Add Anyline Preprocessor

- install.py
#2608
Handle `timm<=0.9.5` statement in requirement.txt added by previous PR.
> Add handling of <= version operator in install.py

- internal_controlnet/args.py
- scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2934.
> More robust ipadapter detection

- scripts/hook.py
> Allow skipping of control type for ControlNet union
