Mikubill/sd-webui-controlnet

scripts/cldm.py, scripts/controlnet.py
Fixes the error shown above when `--device-id` is set to non-zero.
Note that the current implementation of lowvram is suboptimal to say atleast, it should follow the `--lowvram` CLI flag and be compatible with `--device-id`, and follow `modules.devices` API, I will not fix it in this PR.
=> Partially fix --device-id

annotator/hed/__init__.py, annotator/midas/__init__.py, annotator/mlsd/__init__.py, annotator/mlsd/utils.py, annotator/openpose/body.py, annotator/openpose/hand.py
Instead of assuming the default CUDA device is being used, this change will use the torch device from web UI. This is needed if the CUDA device ID web UI is using is not 0, or if the user is running from CPU or MPS (the torch device Macs use).
=> Add support for using the web UI torch device

annotator/uniformer/__init__.py, annotator/uniformer/mmseg/apis/inference.py
This adds support for other torch devices, although more modifications may still be needed to select the correct CUDA device if the default is not being used. Regardless, the changes here shouldn't break anything that currently works.
This PR also fixes the model name for the uniformer model (changes `"body_pose_model.pth"` to `"upernet_global_small.pth"` in `annotator/uniformer/__init__.py`) so it isn't redownloaded every time.
=> Add support for other torch devices to uniformer, fix uniformer model name to prevent unnecessary redownload

preload.py, scripts/controlnet.py
Adds the `--controlnet-dir` cli argument to webui to be able to customize the path to the models. One use case for this is loading control net models from an SSD. I tried keeping the --help text as close to webui's existing options for consistency.
=> Add `--controlnet-dir PTH_DIR` cli argument

scripts/controlnet.py
Because of an oversight in the last PR, when updating, people will run into #65 . This takes into account that cli arguments could have not been registered by the webui.
=> consider preload.py could have not run

annotator/midas/__init__.py
Use CPU instead of MPS for the depth/normal map preprocessor model to workaround the bugs in MPS that produce corrupted depth and normal maps. In most cases it should take less than 2 seconds longer than MPS to generate the depth/normal map. When I have time I'll try to create a better fix if it is possible, but this will at least get the feature functional for Mac users for now.
Also included here is a change to `unload_midas_model()` to fix not sending the model to CPU to unload it from VRAM.
=> Work around corrupted  depth/normal maps with MPS by using CPU for the depth/normal map preprocessor

annotator/hed/__init__.py, annotator/midas/api.py, annotator/mlsd/__init__.py, annotator/openpose/__init__.py, annotator/uniformer/__init__.py
The directory for downloading models are currently hardcoded.
It would be messy when we use a different name for repository directory.
To prevent this, these paths should be expressed as relative path.
=> use relative path for download directory

scripts/controlnet.py
Automatically removes the detectmap from the output images when the img2img batch tab is active. Also removes the `control_net_no_detectmap` in ui setting as it is no more needed.
I'm seeing multiple reports of `AttributeError: 'numpy.ndarray' object has no attribute 'save'`, for example: #46, #119, #134, #139. I'm thinking this should be a more user friendly implementation. If for some reason people still want to include the detectmap in batch processing, it will need additional code.
=> automatically remove detectmap in img2img batch tab

scripts/cldm.py
This will fix Macs needing `--no-half` (by adding dtype casting for `--upcast-sampling`) but also has a significant change - currently the ControlNet models appear to be loaded with full precision by default, this PR changes the precision to match the UNet precision of the loaded model in web UI. Unless there is something I'm missing, this change should significantly reduce VRAM usage for _all_ users that aren't using `--no-half`.
Fixes #87, fixes #68.
=> Use UNet precision, add `--upcast-sampling` support

preload.py, scripts/cldm.py
#143 was intended for CUDA, ROCm, and MPS rather than just MPS, but users reported issues such as #157 and #163 because they are using old versions of web UI that do not have `cond_cast_unet`. This PR removes the MPS checks, but uses `getattr()` to set `cond_cast_unet` and get the value for `dtype_unet` so that nothing should break if `cond_cast_unet` or `dtype_unet` are not defined in web UI.
This also adds a command line option, `--no-half-controlnet`, that allows users to force full precision for the ControlNet models even if web UI is using half precision for the Stable Diffusion models.
=> Fix support for half precision and `--upcast-sampling` on non-MPS devices, keep older web UI version support

scripts/controlnet.py
The guidance strength value was being read from the wrong array index, resulting in a boolean value being written to the output metadata.
=> Fix incorrect guidance strength value in metadata

annotator/leres/leres/depthmap.py
I'm not sure what versions of numpy everyone has, but as 1.19.5 wouldn't install for python 3.10 I figured this should be ok?
```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
=> Fix: AttributeError: module 'numpy' has no attribute 'float' (leres)

annotator/uniformer/__init__.py
Currently, the segmentation preprocessor `upernet_global_small.pth` will be downloaded twice, once by [uniformer/\_\_init\_\_.py#L28](https://github.com/Mikubill/sd-webui-controlnet/blob/d45736038601bf80528d26c7c9dd3ceea13c6842/annotator/uniformer/__init__.py#L28), once by [uniformer/\_\_init\_\_.py#L30](https://github.com/Mikubill/sd-webui-controlnet/blob/d45736038601bf80528d26c7c9dd3ceea13c6842/annotator/uniformer/__init__.py#L30). The one downloaded by L28 was not used.
=> fix(uniformer) fix model loading path

scripts/xyz_grid_support.py
not sure if it's effective🤔
forgot to include it😅
I've made some modifications so that it's easier to add new items to the list. By changing the 'AxisOption(foo)' notation in extra_axis_options list to '*AxisOption(foo, clone=True)', new items will be replicated based on the control_net_max_models_num. However, changes to controlnet.py are required to make these replicated items work.
=> Improvement of xyz_grid_support.py

scripts/controlnet.py
- If p.name is a list and p.name[idx] is None, default is returned.
- If p.name is a list and p.name[idx] does not exist, default is returned.
- If default is a list and default[idx] does not exist, None is returned.
=> Improving the selector function.

scripts/controlnet.py
Fixed `Skip img2img processing when using img2img initial image` skipping img2img even when ControlNet is disabled.
=> don't skip img2img when ControlNet is disabled

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
I replicated the bug-report issue template from the webui repo and updated/removed some sections. Is it okay to do it like this with respect to the license of the webui repo?
Not 100% sure if I adapted the issue template to something that matches this repo's needs. Feel free to mention anything that needs change.
=> add bug-report issue template

scripts/controlnet.py
**Describe what this pull request is trying to achieve.**
Enable ControlNet extension batch support for control images.
**Additional notes and description of your changes**
Currently there's only batch support for inpainting masks. I simply adapted the following inpainting batch support pull request (https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7295/files), but for ControlNet control images instead.
This enables using 1 control image per 1 img2img input image, which helps to create videos combining different techniques, as can be seen here as a result of this technique with a live background and a live pianist I created using these changes: https://www.youtube.com/watch?v=ciMeSHmq0hg 
This change can only be usable after the following Pull Request is approved in …
=> Controlnet batch support

scripts/controlnet.py
Currently, controls for 'enabled' cannot be achieved in the script.
This change will overwrite the attribute corresponding to 'enabled' with valid values.
> any -> overwrite enabled[0]
> [any] -> overwrite enabled[0]
> [None, any] -> overwrite enabled[1]"
=> Enable controls for 'enabled' in the script.

scripts/api.py
small fix when using img2img input image instead of explicit image in `controlnet_units` in the API.
=> fix no input image in API cn unit

scripts/controlnet.py
It is incorrect to scale to fit image. I add more calculations to fix it
|   Input Image  | Output Size    |  Output: AS-IS |  Output: TO-BE |
| :-----| ----: | :----: | :----: |
|  192x264 ![download](https://user-images.githubusercontent.com/18410894/221294989-c3f5a204-d53c-4cb1-81c5-bc2a89b568f3.jpg) | 192x264 | ![00127-1486389336](https://user-images.githubusercontent.com/18410894/221295346-8f74b42b-61a2-4987-b48c-42bf5294a980.png) | ![00131-1486389336](https://user-images.githubusercontent.com/18410894/221296236-7dec15b7-d0a1-4438-860a-fd3dfa63d5c8.png)
| 192x264 ![download](https://user-images.githubusercontent.com/18410894/221294989-c3f5a204-d53c-4cb1-81c5-bc2a89b568f3.jpg) | 264x192 |  ![00119-1486389336](https://user-images.githubusercontent.com/18410894/221295428-9920b7ba-2122-4b …
=> fix: calculate size to fit output image

scripts/xyz_grid_support.py
- any = [any, any, any, ...]
- [any] = [any, None, None, ...]
- [None, None, any] = [None, None, any]
- [,,any] = [None, None, any]
- any, [,any,] = [any, any, any, ...], [None, any, None]
> Enabled Only:
- any = [any] = [any, None, None, ...]
- Whitespace characters are replaced with None.
- The configuration values that correspond to the None index are used from GradioUI.
- There is a difference in behavior between 'Enabled' items and non-'Enabled' items when using 'any' (not in a list).
- Using [] in the filename will cause it to malfunction. Only the [hash value] is allowed.
=> Added support for Multi-ControlNet (list notation).

scripts/api.py
fastapi marks as deprecated the class of any field that has been marked with `.extra['deprecated'] = True`. Using `'_deprecated'` instead seems to fix the issue.
closes #462
=> use private '_deprecated' field to hide deprecated fields from docs instead

scripts/api.py, scripts/controlnet.py
Puts the models cache into a static variable. Could move it to globals too. It may also fix img2img and txt2img not having the same models cache.
closes #429
=> static models cache

scripts/movie2movie.py
- Currently using movie2movie script fails to create gif after successfully generating all the images.
- This issue is caused by wrong path generation in `save_gif` method.
- It seems to be skipping the `date` directory from the output as shown in following image
- We can change the logic in save_gif method to not be dependent on path anymore.
- We can skip the `path_list` and `imgs` variables and use `image_list` directly for saving images and also generating gifs.
- Currently it saves animation.gif in the `txt2img-images` folder directly, I have updated it to be saved in the `txt2iimg-images/controlnet-m2m` folder.
- Added TODO for creating different names for each generation. Let me know if I should remove TODO or complete it.
=> Updated path mechanism for movie2movie to fix FileNotFoundError

scripts/controlnet.py
Small UI addition -- sends the dimensions of a particular ControlNet tab's **current image** to txt2img or img2img. Relates to https://github.com/Mikubill/sd-webui-controlnet/issues/378.
[Franco.webm](https://user-images.githubusercontent.com/93007558/221983147-d9ee91ac-5e74-48f6-940d-71e739f03c8d.webm)
=> Added "send dimensions" button

scripts/controlnet.py
To solve the problem I described in this question: https://github.com/Mikubill/sd-webui-controlnet/discussions/482
When the option "detect map auto-saving" is activated, it saves the maps generated by the pre-processor in the folder detected_map with the corresponding model name.
When the preprocessor is set to none, ControlNet creates a folder none and keeps copying map provided to the extension in this folder. There is no sense to save those maps.
The typical workflow is to generate a map one time providing an image. And then load this map and set the pre-processor to none. With my fix, no none folder and new image files will be generated at each generation.
=> No autosave if preprocessor is none

scripts/xyz_grid_support.py
- Remove the closure for the `confirm()` function and use `functools.partial()` instead.
- Separated the `add_axis_options()` in small pieces: no more nested function inside it.
- `extra_axis_options` is now a dict outside of any function, I think it is possible in the future to make it even simpler to avoid repeating the same pattern for each option.
@aiton-sd: your thoughts about it?
=> xyz_refactor

scripts/controlnet.py
When no_detectmap_opt was set, execution would stop in postprocessing, failing to release (retore) the controlnet from the model and clearing `latest_network` and `input_image`
=> no_detectmap_opt fix

scripts/controlnet.py
More details regarding this PR is mentioned in #567.
- `scripts/controlnet.process` method has now check for image['image'] being str.
- We will convert it to the np.array if it is string using the `modules.api.api.decode_base64_to_image` method.
Fixes #567
=> Add str check for image for API compatibility related to #567

scripts/api.py, scripts/controlnet.py, scripts/external_code.py, scripts/global_state.py
Closes #571, closes #567
This combines the 2 argument passing strategies we use in `processing` and `postprocessing` into a single strategy. (using an array of structures) I find that code readability increases with this.
As I am not sure whether this really is a good idea, I created a companion discussion: #528. This changes a lot of code, risks breaking something as there are no tests. Feel free to close if it is not welcome.
=> Deprecate `/controlnet/*2img` web API in favor of new alwayson_scripts support

scripts/controlnet.py
latest version of controlnet does not perform correct checks if its enabled, so if txt2img is triggered via api call, it will attempt processing even if its disabled.
=> skip process if nothing to do

scripts/api.py, scripts/external_code.py
Add a version to the API, to allow developers to support different API versions with breaking changes.
- new `/controlnet/version` route in web API
- new `external_code.get_api_version() -> int` function in code API
Closes #584
=> Add API version getter

scripts/controlnet.py
`gr.State()` deepcopies the argument you pass to its initializer, this caused some amount of delay on startup since entire components were being passed to it:
https://github.com/gradio-app/gradio/blob/dbd4f755fe634ea30df382c4e0c02303310d8ecc/gradio/components.py#L3001
This PR remedies that by copying the only state necessary, the `elem_id`
=> Improve startup performance by not deepcopying component state

scripts/controlnet.py
In the gradio interface, setting an image to a control unit and then removing it using the "x" button does not effectively clear the image. The last image is always passed to the process function.
=> Fix: clearing a control unit image does not do anything

scripts/controlnet.py
This pull request addresses an issue where the inpaint algorithm did not work correctly with controlnet when the resolution of the input image was different from the resolution of the image used in the controlnet. The solution provided in this PR involves resizing the crop zone so that it is consistent for both images, ensuring that the inpaint algorithm functions as expected.
Fixing a bad hand for example:
The resolution of the image used in the inpainting process is 512x512, while the resolution of the image in the controlnet is 1086x1086. This higher resolution in the controlnet allows for the addition of finer details to the image being inpainted, enhancing its quality and appearance.
=> Fix Inpaint with ControlNet for Different Image Resolutions

scripts/controlnet.py
This PR adds several elem_ids to easier target the controlnet images by other extensions.
The Image Browser I maintain has the option of sending an image to a selectable controlnet image.
However since the Gradio update I haven't been able to consistently target the necessary UI elements. This PR will make it possible again by adding elem_ids.
I suspect other extensions will also benefit from this.
=> Adding elem_ids to target controlnet image

scripts/controlnet.py
The previous code would modify the API input parameters, resulting in the image and mask in the ControlNet parameters in the response being of type ndarray and not being serialized properly when the serialization returns after the generation is complete.
=> Fix response serialization error

scripts/controlnet.py, scripts/hook.py
Probably related to #670 
Previously when using hires fix, the input image would get downscaled to the base resolution, which led to loss in detail and possibly a complete loss of guidance in the hires pass. 
This fixes it by using an image scaled to the hires target resolution for the hires pass.
Here is a very obvious example where the input image gets almost completely ignored:
prompt: 1girl
Negative prompt:  easynegative
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1649927220, Size: 512x512, Model hash: bd83b90a2e, Model: Counterfeit-V2.5, Denoising strength: 0.55, ControlNet-0 Enabled: True, ControlNet-0 Module: none, ControlNet-0 Model: control_canny-fp16 [e3fe7712], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1, Hires upscale: 2, …
=> Use image scaled to target resolution for hires fix

scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/811 (see additional comment below regarding this fix)
As discussed in https://github.com/Mikubill/sd-webui-controlnet/pull/742, the shuffle processor seed should be reproducible but also controllable by the user. The implementation in https://github.com/Mikubill/sd-webui-controlnet/commit/fa994bb2ffed7428f07afd423f215609c5794204 isn't ideal because when using txt2img, this means that only one variation is able to be created for a generated image.
This PR changes this to also account for the subseed (what the web UI refers to as the `Variation seed`). This means that a user could use this variation seed, with the `Variation strength` set to `0` (so it doesn't affect the base generated image), but it will affect the Shuffle …
=> Fix shuffle preprocessor seed bug & allow modifying seed with subseed

scripts/processor.py
this is the only exception that was not handled in the api refactor.
=> cast threshold_a to int for mediapipe

annotator/annotator_path.py, preload.py, scripts/controlnet.py
Now we can put the models where we want. There are 2 ways to specify the preprocessor directories path:
- by command line, using `--controlnet-annotator-models-path <models-directory>`
- by setting the value of the textbox in the controlnet settings: "Path to directory containing annotator model directories (overrides command line flag for annotators path)"
- by not doing anything. default value is `extensions/sd-webui-controlnet/annotator/downloads`
I think the default value should be under `<webui>/models` and users should delete corrupted models manually instead. What do you think @lllyasviel, is that a bad idea? See message here for the rationale behind this: https://github.com/Mikubill/sd-webui-controlnet/pull/881#issuecomment-1512665611
I will update this PR according to the outcome …
=> add settings for annotator models path

scripts/hook.py
Fix mistake in control_scales calculation. This is old bug, but I discovered it when testing new super high quality resampling.
=> fix control_scale calculation for adapter with high_res_fix

install.py, requirements.txt
This PR stops the repetitive mediapipe installation upon each and every webui launch. 
Also removed opencv-python (again), as it comes with 3 of webui's core repos: 
- CodeFormer
- stable-diffusion-stabillity-ai
- taming-transformers
=> Stop repetitive mediapipe install at webui launch

scripts/external_code.py
On some plugins this crashes on object type Nonetype. Figured because the function can return type none it would be a good idea to return type none if we have a variable of type none. There are a lot of nones in this post. Does that make it holly? (sorry for the poor joke, I have been starring at python code all day)
=> Fixed issue where Nontype causes a crash

javascript/hints.js, scripts/controlnet.py
I found the controlnet emoji buttons a little bit confusing. The user might need to try really hard to guess what each button is for. This PR adds a hover tooltip on each `ToolButton` which appears after the user hovers on the button for a while. 
There is a simpler way to display hover text by adding `title` attribute on `button` element[[link]](https://stackoverflow.com/questions/45456543/make-text-show-up-on-hover-over-button).  However, I did not found a way in Gradio to either directly add a custom attribute on button element, or trigger a piece of JS code that add custom attribute to the element on document load. 
So, I have to take a far route which is pure CSS based implementation.
Note:
There is a undesired side-effect on the UI. Gradio has following CSS rule on non-absolute …
=> [UI Improvement] Add hover tooltip for ToolButton

scripts/controlnet.py
When setting up image and mask into nparray... the mask is typically empty. However, when using the API the mask can be an **empty string**, hence controlnet tries to parse the empty string [and causes exception]... So the solution is to check if the incoming mask is a string and is not empty!
Replace
``` python
if isinstance(result['mask'], str):
result['mask'] = external_code.to_base64_nparray(result['mask'])
elif result['mask'] is None:
result['mask'] = np.zeros_like(result['image'], dtype=np.uint8)
```
with
``` python
if isinstance(result['mask'], str) and result['mask']:
result['mask'] = external_code.to_base64_nparray(result['mask'])
else:
result['mask'] = np.zeros_like(result['image'], dtype=np.uint8)
```
EDIT: This was not great... look below! 😄 👇
=> Fix an issue with empty mask string.

javascript/hints.js
the hints (toole tip) used in controlnet overrides the hints used in webui
which extension enabled, the [hints in webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/javascript/hints.js) is broken
this fixes it
I'm not a web developer, so I'm not really familiar with JavaScript, I suspect they might be a more elegant way of fixing this.
=> fix hints (toole tip) for webui when controlnet is enabled

annotator/openpose/__init__.py, scripts/controlnet.py, scripts/controlnet_version.py, scripts/processor.py
This PR adds a link on the page to allow user to download openpose preprocessor result as JSON file.
The link only appears when:
- `Allow Preview` option is checked
- An openpose related model is selected
- Trigger button on preprocessor is clicked
The link will not disappear unless the preprocess is clicked again and another preprocessor is selected.
The JSON file format follows [openpose repo's output format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md).
This is the first step to build an seamless integrated openpose editor(#1012). I will do some research on how to send the JSON to another extension and how to set the preprocessor image in controlnet.
=> [New Feature] Allow user to download openpose preprocessor result as JSON file

annotator/openpose/body.py
The pipe operation on type annotation is introduced in Python 3.10. See [PEP 604](https://peps.python.org/pep-0604/).
User ran into issue when running with 3.8. 
Add back type annotation as it is a problem with the user's setup. 
Note:
I am not pumping up version in this PR as type annotation does not affect code execution.
=> Add back type annotation on BodyResult

scripts/api.py, scripts/controlnet_version.py, tests/utils.py, tests/web_api/detect_test.py
I noticed that the `detect` API call returns with a `200` status code when the selected module is not implemented/available or no when no input image is provided.
This PR raises an 500 status code HTTP exception for better integration with 3rd party implementations.
Note: I couldn't find a PEP formatting guide on the repo, so I didn't format the file on saving to avoid having unrelated changes on the PR.
=> fix: Raise 500 exception instead of returning an error on `detect` API call

scripts/api.py, scripts/controlnet.py, scripts/external_code.py, scripts/processor.py, tests/utils.py, tests/web_api/txt2img_test.py
I'm contributing to the [Auto-Photoshop-StableDiffusion-Plugin](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin)
When I was implementing the ThresholdA/B in it, I found that all the sliders config is hardcoded in sd-webui-controlnet.
I think it is better to expose them in the API, so external tools like [Auto-Photoshop-StableDiffusion-Plugin](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin) or plugin in Blender etc. could build ThresholdA/B sliders without hardcoding the settings of sliders in their code.
=> fetch sliders_config by `/controlnet/module_list`

scripts/processor.py
Thanks for you patiently correction in #1166
------
here is a liitle bugfix:
when preprocessor is none and keep recheck/uncheck PixelPerfect, the resolution slider will show,
the bug is existed before #1166
=> little bug fix: preprocessor is none but has resolution slider

scripts/controlnet_version.py, scripts/hook.py
It seems work now
this is a midjourney image as input (https://www.reddit.com/r/midjourney/comments/11wsoy8/random_people_on_the_streets/)
this is before fix (1.1.162)
this is after fix (1.1.163)
Image is not perfect since I am not using any advanced method - just a low res diffusion pass with 20 Eluar A steps
meta:
handsome man in street, masterpiece, best quality, 4k, 8k, hat
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Steps: 20, Sampler: Euler a, CFG scale: 5, Seed: 123456, Size: 768x512, Model hash: c0d1994c73, Model: realisticVisionV20_v20, Clip skip: 2, Version: v1.2.0, ControlNet 0: "preprocessor: reference_only, …
=> try to fix collapse in ref-only

scripts/controlnet.py, scripts/controlnet_version.py, scripts/hook.py, scripts/processor.py
Since different people have different preferences, we will add a Style Fidelity Slider slider since 1.1.168
This slider only work in "balanced" mode
higher value mean more fidelity in style, but also more risk to collapse
lower value mean less fidelity in style, but also more robust
=> Style Fidelity Slider

scripts/controlnet.py, scripts/controlnet_version.py, scripts/global_state.py, scripts/hook.py, scripts/processor.py
V1.1.171 adds two new reference preprocessors:
**reference_adain**
AdaIn (Adaptive Instance Normalization) from
Arbitrary Style Transfer in Real-time with Adaptive Instance Normalization
https://arxiv.org/abs/1703.06868
**reference_adain+attn**
AdaIn (Adaptive Instance Normalization) + Attention link same as "reference_only"
source (midjourney v5, https://twitter.com/kajikent/status/1654409097041817601)
meta
woman in street, masterpiece, best quality,
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 768x512, Model hash: c0d1994c73, Model: realisticVisionV20_v20, …
=> add preprocessor reference_adain and adain_attn

.github/ISSUE_TEMPLATE/bug_report.yml
More and more issues are being opened that are caused by other 3rd party extensions that should be reported upstream but are not (https://github.com/Mikubill/sd-webui-controlnet/issues/1301, https://github.com/Mikubill/sd-webui-controlnet/issues/1284, https://github.com/Mikubill/sd-webui-controlnet/issues/1239, https://github.com/Mikubill/sd-webui-controlnet/issues/1296, https://github.com/Mikubill/sd-webui-controlnet/issues/1265). This PR adds a new requirement to creating bug reports that asks for a list of all enabled extensions.
I'm going to open a PR in the main web UI repo soon to add a button or similar to copy the list of enabled extensions for easy pasting, but hopefully we could add this now to narrow down the amount of bogus reports we're receiving.
=> Add enabled extension list requirement to bug reports

scripts/controlnet_version.py, scripts/hook.py
This is an attempt to address most collapse problems of the reference preprocessor.
Now we are using time step to guide the scale, but it is wrong from a mathematic perspective - this commit brings a real cfg-like guidance, which leads to significantly fewer artifacts.
=> shift to cfg-scale based style fidelity

scripts/controlnet.py
Currently, sliders in ControlNet use the `change` event, which is very sluggish when modifying values. This changes it to use `release` instead, resulting in much better visual performance.
<details>
<summary>Current behavior</summary>
</details>
<details>
<summary>New behavior</summary>
</details>
(Ignore offset slider positions, it's due to my txt2img panel size)
=> Improve slider UI performance

preload.py, scripts/api.py, scripts/controlnet.py, scripts/controlnet_version.py, scripts/global_state.py, scripts/utils.py, tests/cn_script/utils_test.py
#807 attempts to add a cache for preprocessor, but using an inefficient way:
- Use str(ndarray) as hash will make array with same start & end return same hash
- Each time the preprocessor is called, the caching decorator is reapplied
#1238 also requests us adding cache for preprocessor.
This PR adds an shared LRU cache of size 16 for all preprocessor functions. We can debate the cache size later. I set it to 16 as I feel like I often don't need longer history of preprocessor results.
Currently openpose preprocessor will not be cached when called with trigger button in preview, as each time the preprocessor receives a new instance of `JsonAcceptor`. We probably will want to rework the function signature of preprocessor later so that openpose preprocessor can be cached as well.
=> [Enhancement] Cache preprocessor results

scripts/global_state.py
Shuffle preprocessor calls `np.random`, which makes the function impure, i.e. returns different value each time with same parameter given. 
Maybe we should consider adding a seed parameter to the preprocessor?
For now, the quick fix is to exclude it from the caching mechanism.
=> Exclude shuffle from preprocessor cache

scripts/api.py, scripts/external_code.py
In the Auto-Photoshop plugin, we extract the number of ```control_net_max_models_num``` from the ```/config``` endpoint. However, this doesn’t always work due to user interface localization as in [this]( https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/266). 
This pull request makes it easier for third-party tools to get the number of max units from the API.
=> Fetch control_net_max_models_num settings from the api

scripts/controlnet.py, scripts/controlnet_version.py, scripts/processor.py
Beginning from 1.1.192, we will add a quick shortcut in UI, the Control Type filter.
You can turn off this quick filter in setting if you prefer not to have it, using the option “Disable control type selection”:
This filter has two functionalities:
First, if you select one type of control, your preprocessor list and model list will only show items of that type. You can always select “All” to see all preprocessors/models just like before. For example, I select “depth”
Then
Second, if you select one type of control, it will automatically select a default combination of that control. For example, I select “depth”
Then
Note that this filter has nothing to do with API and code logics so it will has zero influence to all other extensions.
Now we can swift methods much easier. And we do not need …
=> [UI Update] The Control Type Filter is finally implemented

scripts/controlnet_version.py, scripts/global_state.py, scripts/hook.py, scripts/processor.py
**1.1.195** added preprocessor tile_colofix.
This preprocessor is mainly targeted to a problem of tile that sometimes it causes color offsets.
**meta (in txt2img, similar to img2img with denoising strength 1.0)**
1girl, best quality
Negative prompt: lowres, bad anatomy, bad hands, cropped, worst quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 512x640, Model hash: 8712e20a5d, Model: Anything-V3.0, Clip skip: 2, Version: v1.2.1, ControlNet 0: "preprocessor: tile_XXXX, model: control_v11f1e_sd15_tile [a371b31b], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (64, 1, 64)"
**input image (64px)**
zoom in view (for visualization, not used)
**tile_resample:**
**tile_colorfix (all parameters …
=> add tile_colorfix

scripts/controlnet_version.py, scripts/global_state.py, scripts/hook.py, scripts/processor.py
**1.1.196** added "tile_colorfix+sharp"
This method allows you to control the latent sharpness of the outputs of ControlNet tile.
This preprocessor can prevent the Tile model from the tendency to create the somewhat blurred "harmonious atmosphere" in your upscaled images.
Input image (480x640)
Meta (Using T2I or I2I with 100% denoising strength, no extra upscaler/super-resolution, all results use same seed 12345):
1girl, best quality
Negative prompt: lowres, bad anatomy, bad hands, cropped, worst quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 960x1280, Model hash: 8712e20a5d, Model: Anything-V3.0, Clip skip: 2, Version: v1.2.1, ControlNet 0: "preprocessor: tile_XXXX, model: control_v11f1e_sd15_tile [a371b31b], weight: 1, starting/ending: (0, 1), resize mode: Crop …
=> add tile_colorfix+sharp

scripts/controlnet.py, scripts/global_state.py, scripts/ui/controlnet_ui_group.py, scripts/ui/controlnet_unit.py, scripts/utils.py
This is large refactoring PR that moves out the bulk UI logic out from `controlnet.py`.
The `ControlNetUnit` UI class split the original logic into 3 main parts:
- render: Pure HTML layout
- register_callbacks: All event handlers attached on the gradio elements
- render_and_register_unit: Handle unit related operations (and batch operations?)
I have tested locally on the functionalities I am familiar with. 
@ljleb can you help verify batch script still works?
Feel free to revert this PR if it breaks things after merge.
P.S. It is not viable to unit test the original `uigroup` method as too many things are involved.
=> [Refactor] Move controlnet.Script.uigroup out as ui.controlnet_ui_group

scripts/controlnet.py
After so many users reporting they cannt find where to enable multi-controlnet, we will by default set 3.
=> Change to default multi control

scripts/controlnet.py
This PR moves the logic of picking the input image out of the gigantic `Script.process` function. 
Choose input image from following sources with descending priority:
- p.image_control: ????
- p.control_net_input_image: ????
- unit.image: 
- ControlNet tab input image.
- Input image from API call.
- p.init_images: A1111 img2img tab input image.
Can someone explain what are the first 2 branches for?
=> [Refactor] Move choose input image logic out of Script.process

scripts/controlnet.py
Remove the unnecessary copying of `input_image` as it will be done again later
```
try:
tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed), 0))
tmp_subseed = int(p.all_seeds[0] if p.subseed == -1 else max(int(p.subseed), 0))
np.random.seed((tmp_seed + tmp_subseed) & 0xFFFFFFFF)
except Exception as e:
print(e)
print('Warning: Failed to use consistent random seed.')
input_image = np.ascontiguousarray(input_image.copy()).copy() <<<<<
print(f"Loading preprocessor: {unit.module}")
preprocessor = self.preprocessor[unit.module]
h, w, bsz = p.height, p.width, p.batch_size
```
=> remove unnecessary copying

scripts/controlnet.py, tests/cn_script/cn_script_test.py
Previously `a1111_mask` variable was reassigned to hold value of different type, which caused crashes. This reland fixes this by rename the `a1111_mask` with `PIL.Image.Image` type as `a1111_mask_image` so that variable types are stable. 
Verified locally that the issue is fixed in inpaint mode.
=> [Reland] Extract Prepare Mask logic

scripts/external_code.py
A1111 has an extra `ResizeMode` enum value 3 for "Just resize (Latent Upscale)". Make it fall back on ResizeMode.RESIZE.
Also make other unrecognized resize mode value fall back on ResizeMode.RESIZE so that we don't get list out of bound exception.
=> :bug: Handle unrecogznied resize mode value

README.md, preload.py, scripts/controlnet_version.py, scripts/logging.py
This PR adds a logger to help distinguish different levels of logs. The default log level is set to `INFO`. 
Example log of ControlNet version:
```
2023-06-02 18:01:51,483 - ControlNet - INFO - ControlNet v1.1.213
```
We should be able to slowly migrate to using the logger from unconditional print.
=> Add logger

scripts/api.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/external_code.py, scripts/global_state.py, scripts/logging.py, scripts/utils.py
This PR migrates most `print` under `scripts/` to corresponding `logger` functions. 
This PR also fixes the issue that a second handler can be added to the logger when module reloaded.
=> Logging migration

scripts/api.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/external_code.py, scripts/global_state.py, scripts/logging.py, scripts/utils.py
Previously there was an error output to `stdout` instead of `stderr` in ControlNet code. This caused issue when the logger outputs error message to stderr.
This reland excludes the error code. 
Filed #1541 to track unittest fix.
=> Reland logging migration

scripts/controlnet_ui/controlnet_ui_group.py, tests/cn_script/batch_hijack_test.py
This PR adds a `preview as input` that allow user to force ControlNet use the preview image as input image.
This is especially useful if user is not satisfied with proprocessor result, did some edits on preprocessor preview image and want to use the preview image as input.
This is the pre-work of #1454.
=> Add `preview as input` button

scripts/logging.py
This PR disables propagate of the controlnet logger so that log messages do not appear again in the root logger.
=> :bug: Disable logging propagate

scripts/logging.py
This PR also moves log output from `stderr` to `stdout`. 
`stderr` appears red by default in PyCharm.
=> :art: colorize loglevel

javascript/active_units.js, style.css
This PR adds a total enabled unit count badge besides the ControlNet accordion. 
Light theme:
Dark theme:
=> :art: Add active units count badge

javascript/openpose_editor.js, scripts/controlnet_version.py
Some users reported that they think openpose is not working when they see ⚠️
so we will change this to \<del\>
=> change openpose error icon

javascript/openpose_editor.js, scripts/controlnet_ui/openpose_editor.py
Previously every controlnet unit had an openpose editor iframe embedded invisible. However, the user most likely will only use one controlnet unit for openpose control. Loading the editor in every unit is obviously introducing uncessary work and memory usage (Each Vue app is about 0.5MB size). This become especially true if the user has a lot of controlnet units in the settings. 
This PR makes openpose lazy load on the first click on the edit button.
When navigating the iframe, we wait either 1s or receiving a `ready` frame message from the iframe. The 1s delay should be sufficient under most local setup. Even if the frame message is sent when the iframe is not ready, the user still can close the modal, and reclick the edit button.
=> Lazy load openpose editor iframe

style.css
Before:
You see there are double scroll bar on the right, even the modal iframe do not need that much space.
After:
The modal does not introduce another scrollbar when it's unnecessary.
=> :art: Make modal content fit the window size

javascript/openpose_editor.js
Openpose editor supports dark theme param in v0.1.4. 
This PR passes the theme parameter to openpose editor based on WebUI's theme.
=> :art: Pass dark theme param of A1111 to openpose editor

annotator/pidinet/model.py
When I used softedge_pidinet preprocessor, I got a RuntimeError like this
```
Error running process: F:\github\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
File "F:\github\stable-diffusion-webui-directml\modules\scripts.py", line 451, in process
script.process(p, *script_args)
File "F:\github\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 805, in process
detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
File "F:\github\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
return cached_func(*args, **kwargs)
File …
```
=> fix: runtime error for directml in pidinet

scripts/controlnet_ui/controlnet_ui_group.py
The PR fixes the unmatched output parameter number when image is None for `run_annotator` function.
=> :bug: Fix output of run_annotator

scripts/controlnet.py, tests/cn_script/cn_script_test.py, tests/web_api/txt2img_test.py
This PR refactors the logic of bound check parameters for API calls.
- Removes the try-catch default value check, as it might hide underlying issues, such as no `"value"` present in config.
- Only use default value and print warning when a required value is invalid.
=> [Reland] 🔨 Refactor bound check for threshold and resolution

scripts/controlnet.py, scripts/global_state.py
This PR addresses #1672.
`global_states.cn_detectedmap_dir` is not used anywhere else in the code, thus removed.
https://github.com/Mikubill/sd-webui-controlnet/blob/16805be062f44feee4513a39349a1ed83595279e/scripts/controlnet.py#L929 already does the makedir work so it should be fine to just remove the makedir in global_states.
=> :bug: Remove mandatory mkdir for detected_maps

scripts/external_code.py
We have plenty of issues caused by A1111 screwup the script args parsing due to extension conflicts. This PR adds a typecheck to ensure that a meaningful error message is printed out.
https://github.com/Mikubill/sd-webui-controlnet/issues?q=is%3Aissue+%22has+no+attribute+%27enabled%27%22
=> Add typecheck on script args

javascript/active_units.js
This PR implemens a feature requested in https://github.com/Mikubill/sd-webui-controlnet/discussions/1703.
Now on new image upload, the `enable` checkbox is automatically checked.
=> :art: Auto enable unit on image upload

javascript/img2img_input_display.js, style.css
I found that many people don't know that if you do not upload an image in the ControlNet UI in img2img mode, the img2img input will be used as input to ControlNet.
This PR address this issue by setting the A1111 img2img input as background image in all ControlNet units. This will allow user realize that A1111 input will be used as fallback.
[screen-capture (3).webm](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/08d136ad-b31d-46c3-9557-5495ae00bbf2)
Note:
One drawback is that the user might click `run preprocessor` button with A1111 input as background and nothing happens. I think one way to address this is to display an error message on UI saying that no ControlNet input image.
=> :sparkles: Display A1111 input as fallback image in img2img

web_tests/main.py
Previously the img compare threshold is too low that many compare fails even the image matches. This PR increase the abs diff tolerance to 1 (where value ranges from 0 to 255)
=> :wrench: Increase img compare diff tolerance

scripts/controlnet.py, scripts/utils.py
Do not merge until A1111 side [PR on custom metaclass](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11264) landed. 
This PR adds debug timing logs to `Scripts` to better understand performance bottlenecks. 
Source bug: #1648
=> :loud_sound: Add timing debug logs

javascript/active_units.js
This PR adds the control type to tab name so that users can have better idea which tab to navigate to.
=> :art: Display control type on tab selection button

javascript/openpose_editor.js
See:
https://github.com/huchenlei/sd-webui-openpose-editor/issues/32
Suspect on slower machines, the initial load of the iframe can take longer than 1 second. If 5s is still giving the error, we should consider introduce a handshake mechanism.
=> :wrench: Wait longer for openpose editor iframe to respond

javascript/active_units.js, web_tests/main.py
According to https://github.com/Mikubill/sd-webui-controlnet/discussions/1143, when using inpaint, ControlNet input should be left blank, and ControlNet will by default fallback onto the A1111 img2img input. However, our front-end code does not enforce user leave the input blank. User can still upload an irrelevant image as ControlNet input, and apply a mask on that image. This can cause very undefined and controversial behaviours, e.g.
- When both masks exists, current code picks the mask from A1111, but the ControlNet input image is picked.
- https://github.com/Mikubill/sd-webui-controlnet/issues/1743
- The generation result does not make sence when img2img input and ControlNet input are not the same image
For these considerations, this PR disables the ControlNet image input when user …
=> :wrench: Disable ControlNet input in img2img inpaint

javascript/active_units.js, style.css
In img2img when using A1111 input, the resize mode from A1111 will be used. The resize mode set in ControlNet UI will be ignored.
This PR disables the resize mode selection when using A1111 input in img2img mode so that it is clear that the value is not being used by the backend.
=> :wrench: Disable resize mode selection when using A1111 input

scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/1811
This exposes the Gaussian blur sigma value used for inpainting (currently hardcoded at an arbitrary value of `7`), which can allow for a more smoother transition in some cases, especially for txt2img outpainting. The default value remains at `7`.
You can see a before/after comparison here: https://imgsli.com/MTkzMzYw
(image from https://github.com/Mikubill/sd-webui-controlnet/discussions/1597#discussioncomment-6401743)
---
I believe this could still be improved but I'm not sure the best way to go about implementing a proper fix. An additional final pass in img2img + manual feathering may be the only way to 100% resolve it for the time being.
cc @wywywywy if you would like to test this out as well.
=> Controllable inpainting Gaussian blur sigma value

scripts/api.py
add a parameter in the method `/controlnet/model_list` to allow user to set whether to update model
=> update model_list to allow to set whether to update model

scripts/controlnet.py, scripts/hook.py
Closes #1826
Adds an option in settings to disable ControlNet in highres fix. I'm not 100% sure if this breaks anything so I'm setting this as a draft for now. I also cannot produce anything that causes a "big negative impact" as mentioned in the issue, as in my tests images look nearly the same with or without this setting enabled, but that does mean it can cut down generation times in half with minimal change to the final output, so I figure it's a nice QoL feature to have.
=> Add setting to disable ControlNet in highres fix pass

scripts/controlnet.py
Closes #1834
Checks if an SDXL model is loaded directly after checking if any CN units are enabled, and will exit the process function with a console warning if so.
=> Disable ControlNet if model is SDXL

annotator/openpose/__init__.py
Users have reported having problem installing `mmpose` which is required by DW Pose. This PR delays the import of mmpose to the actual run of `dw_openposefull_preprocessor`, so that other parts of ControlNet still remains functional even when DW Pose has some problems installing dependencies.
#1864
#1865
=> :bug: Delay import of mmpose

annotator/openpose/util.py, annotator/openpose/wholebody.py
Closes #1870.
This PR handles the case where all body keypoints are `None`.
=> :bug: Fix all keypoints invalid issue

scripts/processor.py
Closes #1873. 
This PR lazy imports `mmengine` so that when mmengine failed to install, all other functionalities of ControlNet remain useable.
=> :bug: lazy import mmengine

javascript/active_units.js, javascript/hints.js, javascript/img2img_input_display.js, scripts/controlnet_ui/controlnet_ui_group.py
In response to issue https://github.com/Mikubill/sd-webui-controlnet/issues/1867 and related to PR [#1747](https://github.com/Mikubill/sd-webui-controlnet/pull/1747), I suggest those modifications to the Javascript code.
The run preprocessor button is enabled only if an image input exists in the ControlNet input tab. The hint of the button is changed accordingly.
One problem I have:
at the first start of webui, the button is enabled without any input image. I don't know where in the code I can change this initial state. But I don't think it is a big issue as the user will not expect any result with a totally blank canvas I believe.
=> disable run preprocessor if no cn input image

install.py, requirements.txt
User has reported that opencv 4.5.5 cannot run onnx model. https://github.com/Mikubill/sd-webui-controlnet/pull/1892#issuecomment-1671727728
This PR adds the opencv dependency with a known good version.
=> :bug: Add dependency on opencv 4.8.0

install.py, requirements.txt
Reverts Mikubill/sd-webui-controlnet#1897
pip install opencv-python>=4.8.0 does not perform the package upgrade correctly in local testing.
=> Revert ":bug: Add dependency on opencv 4.8.0"

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/1651.
This PR makes the `have_mask` check less strict, as sometimes gradio will give masks with some `1`s in it as reported by the users. 
This PR also offers an option for users to ignore ControlNet input mask in non-inpaint modes, as the input mask is generally not very useful in other control types.
=> Add option to ignore ControlNet input mask in non-inpaint modes

scripts/controlnet.py
Resolves https://github.com/Mikubill/sd-webui-controlnet/discussions/1888, https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12428
This has been broken for about 3 months now and was never accounted for in this extension. The webui switched from using `mask_blur` to separate attributes for `mask_blur_x` and `mask_blur_y` in 1.4.0, so the `mask_blur` was read as `None` by ControlNet. https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/10295
Uses the same code from here to modify the mask: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/26c92f056acc795af5066779f1b8aedb8dfa983d/modules/processing.py#L1287-L1297
=> Fix mask blur

annotator/openpose/wholebody.py
This PR fixes an issue where DWPose is outputing only 68 keypoints for face, but openpose spec defines 70 keypoints. https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md
This should fix the missing face issue in openpose editor.
=> :bug: DWPose face keypoint num fix

javascript/img2img_input_display.js, scripts/controlnet_version.py
show image of a1111 in i2i preview is a good idea in theory, but in reality it is just annoying and misleading. take a look at issue and we are going to remove it
=> remove annoying i2i preview

scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/openpose_editor.py, scripts/controlnet_version.py
smart preview management, remove preview as inputs
I tested openpose editor.
Please test yourself to see if anything is missing
=> smart preview management, remove preview as inputs

javascript/active_units.js, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/infotext.py, tests/cn_script/batch_hijack_test.py
Closes #1793
This was broken (and has been for quite some time now) after ControlNet params started being stored altogether as part of a single key and not separate keys per param. The ideal solution would be rework how this is handled altogether so it accounts for more parameters in a cleaner way, but this is just patching the functionality that previously existed for now.
This also allows the `Parse ControlNet parameters in infotext` setting (previously titled `Passing ControlNet parameters with "Send to img2img"` which is unclear and technically incorrect since it also applies to txt2img) to be handled at runtime rather than requiring a restart of the webui, as the setting previously was only taken into account during the UI creation process.
~~Setting as a draft because …
=> Repair ControlNet infotext parsing

scripts/infotext.py
User has reported the assertion got triggered in https://github.com/Mikubill/sd-webui-controlnet/issues/1966.
This PR converts the check to a soft one that does not block generation.
=> No blocking generation on infotext failure

scripts/controlnet_ui/controlnet_ui_group.py
Trying to slove issue in https://github.com/Mikubill/sd-webui-controlnet/issues/1966.
Based on the log, the `clear_slider_update` gr.update dict is being used as the value of another gr.update dict.
=> Deep copy gr.update dict

javascript/canvas.js, scripts/controlnet_ui/controlnet_ui_group.py
currently it only works with when `Multi ControlNet: Max models amount` > 1
I took a shortcut in not checking if `window.applyZoomAndPan` is a function because 
`window.applyZoomAndPanIntegration` is a new addition, and if it is a function then `window.applyZoomAndPan` also is function 
this is a new feature of gradio
and we have already applied it into 1.6.0 RC
which can be seen in the webui 1.6.0 RC or dev, but cannot be seen in master
I did a quick test and it seems that this doesn't break the current master 1.5.2, so hopefully it is backwards compatible with previous versions as well
I'm using the same settings key with img2img inpaint canvus in 1.6.0RC `shared.opts.img2img_inpaint_mask_brush_color`
but you may want to separate it out into a different key
screenshot of canvus zoom …
=> Fix zoom and mask brush color customizable

.gitignore, javascript/active_units.js, javascript/hints.js, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/preset.py, scripts/controlnet_ui/tool_button.py, scripts/infotext.py
Users have requested to be able to save easily save and load controlnet unit presets in https://github.com/Mikubill/sd-webui-controlnet/issues/1854.
This PR implements a preset manager UI that allows users to save/load ControlNet unit presets. Presets are persisted locally as text file under `presets/`.
Known issues:
- Preprocessor sliders values are not populated due to issue mentioned in #1833 .
- Toolbuttons are having wrong hover hint.
=> [New Feature] ControlNet unit preset management

javascript/active_units.js, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/preset.py
This PR makes preset manager update `ControlType` when applying a preset.
Feature discussion: https://github.com/Mikubill/sd-webui-controlnet/pull/1974#issuecomment-1692711347
=> Update control type in preset

scripts/controlnet_ui/preset.py
We need to rework the whole UI update logic later. This PR is just a temporary fix.
Before the fix, preprocessor/slider values will be overwritten by ControlType/Preprocessor updates, when applying preset.
=> :bug: Fix preset application

javascript/hints.js, scripts/controlnet_ui/preset.py
This PR adds a reset button to reset UI states to the state specified in the selected preset.
Known issue:
The state update takes MANY gradio updates right now, as we need to guarantee that the last apply call becomes stable and not triggering other updates.
Note:
I was planning to use `.success` to replace `.then` call so that we could potentially reduce number of calls if there is no change to `control_type` / `module`. However, if a gradio callback has exception, the all IO elements the call outputs to will be forever loading. Maybe we should propose a change in gradio?
=> Add reset preset button

javascript/hints.js, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/preset.py
Some changes made in this PR:
- Re-format ui group file
- Make sliders always interactive as value cannot be populated if the slider is not interactive
- Improve load speed by introducing server side counters to prevent value update when their values > 0 (This can lead to a solution to the paste PNG info of slider values)
This PR adds a `reset` button that allows users to restore to the original state of currently selected preset. Previously, user had to select `New Preset` and then select original preset again to overwrite the changes they made on the UI.
=> Add reset button for preset

javascript/active_units.js
Previously img2img UI is simplified in https://github.com/Mikubill/sd-webui-controlnet/pull/1956.
The new UI logic hides resize mode completely when using independent input image is not checked. This PR removes duplicated control logic on resize mode.
=> :fire: Remove resize mode js logic

scripts/api.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2088
Title. Fixes an error like below that would come up.
```shell
*** Error executing callback app_started_callback for Q:\AI\git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py
Traceback (most recent call last):
File "Q:\AI\git\stable-diffusion-webui\modules\script_callbacks.py", line 139, in app_started_callback
c.callback(demo, app)
File "Q:\AI\git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 89, in controlnet_api
controlnet_input_images: List[str] = Body([], title="Controlnet Input Images"),
NameError: name 'List' is not defined
```
=> Fix missing typing for `List`

scripts/controlnet.py
`process_has_sdxl_refiner` is a static method on `Script`. Calling it with `self.` prefix will cause issue when the method is decorated by
```python
def timer_decorator(func):
"""Time the decorated function and output the result to debug logger."""
if logger.level != logging.DEBUG:
return func
@functools.wraps(func)
def wrapper(*args, **kwargs):
start_time = time.time()
result = func(*args, **kwargs)
end_time = time.time()
duration = end_time - start_time
if duration > 1e-3:
logger.debug(f"{func.__name__} ran in: {duration} sec")
return result
return wrapper
```
in debug loglevel, as `self.process_has_sdxl_refiner(p)` will be interpreted as `process_has_sdxl_refiner(self, p)`, but the function only accepts single param.
This PR fixes the issue by replacing `self.` with `Script.` in all …
=> Fix debug loglevel

javascript/openpose_editor.js
A1111 1.6.0 will automatically open a page in the browser, when the backend extensions were not fully initialized yet. This causes https://github.com/huchenlei/sd-webui-openpose-editor/issues/53 where `checkEditorAvailable` runs before the editor endpoint has been mounted yet.
Since we recently deployed the editor on https://huchenlei.github.io/sd-webui-openpose-editor/, this PR makes a fallback onto the remote editor when local version is not available. This also means users can now access the editor even they do not have the editor extension installed.
The local version is still preferred as it is generally faster, and some users in mainland China can have bad connection to github.com domain.
=> Fallback to remote openpose editor when no local installation found.

scripts/controlnet_ui/controlnet_ui_group.py
Things like changing Control Type/Preprocessor and showing/hiding controls (preview, new canvas, camera, sliders) are snappier without all those loading animations.
=> Don't show progress for UI actions

scripts/controlnet_ui/preset.py
Some control types now have multiple maching clauses for both module and model. E.g. `Tile/Blur` and `Scribble/Sketch`. This PR fixes the issue where `infer_control_type` fails to handle those composite control types.
=> Fix control type fill in preset

internal_controlnet/external_code.py
fix for https://github.com/Mikubill/sd-webui-controlnet/issues/2132 https://github.com/Mikubill/sd-webui-controlnet/issues/2111
=> Update external_code.py   fix for issue 2132 2111

internal_controlnet/external_code.py
This PR keeps `p.script_args` type consistent with `p.script_args_value` before/after calling `update_cn_script_in_processing`. This PR handles the issue where `p.script_args` is `tuple`.
This PR is verified to fix ADetailer issue https://github.com/Mikubill/sd-webui-controlnet/issues/2200.
=> Relands #2133

annotator/anime_face_segment/LICENSE, annotator/anime_face_segment/__init__.py, scripts/global_state.py, scripts/processor.py
#2127 
match this model
[bdsqlsz_controllllite_xl_segment_animeface_V2](https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/bdsqlsz_controllllite_xl_segment_animeface_V2.safetensors)
COLOR_BACKGROUND = (255,255,0)
COLOR_HAIR = (0,0,255)
COLOR_EYE = (255,0,0)
COLOR_MOUTH = (255,255,255)
COLOR_FACE = (0,255,0)
COLOR_SKIN = (0,255,255)
COLOR_CLOTHES = (255,0,255)
=> Add preprocesser for anime face segment

scripts/utils.py
This PR reduces duration measurement in `Script` functions to 3 decimal points.
Sample logs after change:
```
2023-11-04 17:00:32,572 - ControlNet - DEBUG - Create LRU cache (max_size=16) for preprocessor results.
2023-11-04 17:00:32,573 - ControlNet - DEBUG - __init__ ran in: 0.001 sec
2023-11-04 17:00:32,700 - ControlNet - DEBUG - uigroup ran in: 0.031 sec
2023-11-04 17:00:32,731 - ControlNet - DEBUG - uigroup ran in: 0.030 sec
2023-11-04 17:00:32,766 - ControlNet - DEBUG - uigroup ran in: 0.034 sec
2023-11-04 17:00:32,767 - ControlNet - DEBUG - ui ran in: 0.098 sec
```
=> :loud_sound: Reduce debug log duration precision

tests/utils.py
In most recent version of A1111. `module.initialize.initialize` is only expected to be called once. Calling it multiple times gives following error:
```
ERROR extensions/sd-webui-controlnet/tests/annotator_tests/openpose_tests/detection_test.py - RuntimeError: patch for register_schedule is already applied
ERROR extensions/sd-webui-controlnet/tests/annotator_tests/openpose_tests/json_encode_test.py - RuntimeError: patch for register_schedule is already applied
ERROR extensions/sd-webui-controlnet/tests/annotator_tests/openpose_tests/openpose_e2e_test.py - RuntimeError: patch for register_schedule is already applied
ERROR extensions/sd-webui-controlnet/tests/cn_script/batch_hijack_test.py - RuntimeError: patch for register_schedule is already applied
ERROR …
```
=> :bug: Init webui only once in tests

scripts/hook.py
Using IP_Adapter_sd15, It can somehow fail to attach control params before hook.
I found that somehow it is restoring control_params to None, which is causing some weird error when we try to generate image with no prompt after using controlnet:
And the full stack trace goes:
```
Traceback (most recent call last):
File "C:\debug-webui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 855, in forward_webui
return forward(*args, **kwargs)
File "C:\debug-webui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 491, in forward
for param in outer.control_params:
TypeError: 'NoneType' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
=> Set scripts.hook - control_params as empty list at default / Fix TypeError

tests/annotator_tests/openpose_tests/openpose_e2e_test_disabled.py
This PR disables `openpose_e2e_test` as it is verified to be flaky on CI.
=> :bug: Disable flaky tests

.github/workflows/tests.yml, tests/utils.py
Closes #2230.
This PR also switches the model used for tests to an up-to-date sd1.5 model.
=> :wrench: Setup CI cache

internal_controlnet/external_code.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, tests/web_api/txt2img_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/1432.
This PR adds a new API option `send_detected_map`. This option allows users prevent the detected map image in the response image array to save web traffic.
Notes: 
- The option will be captured in the ControlNet infotext, but will not be adjustable in WebUI for now.
- The option is per ControlNet unit, so if you use multiple ControlNet units, you need to specify this option in every unit.
- Adding a global level args in the API is not possible as it would need change in A1111 repo.
=> :sparkles: Add new API option send_detected_map

scripts/enums.py, tests/README.md, tests/annotator_tests/openpose_tests/body_test.py, tests/annotator_tests/openpose_tests/detection_test.py, tests/annotator_tests/openpose_tests/json_encode_test.py, tests/annotator_tests/openpose_tests/openpose_e2e_test_disabled.py, tests/cn_script/batch_hijack_test.py, tests/cn_script/cn_script_test.py, tests/cn_script/utils_test.py, tests/external_code_api/external_code_test.py, tests/external_code_api/importlib_reload_test.py, tests/external_code_api/script_args_test.py, tests/utils.py, tests/web_api/control_types_test.py, tests/web_api/detect_test.py, tests/web_api/img2img_test.py, tests/web_api/txt2img_test.py
This PR let users use SDXL models when running tests. This is a part of larger effort of having more SDXL test coverage described in #2231.
Users can specify sd version via environment variable `CONTROLNET_TEST_SD_VERSION`.
1 for SD1.x
2 for SD2.x
3 for SDXL
SDXL tests are only runnable locally right now, as downloading the 5GB SDXL base model on CI machine is not really viable.
=> :wrench: Support SDXL in tests

.github/workflows/tests.yml, scripts/controlmodel_ipadapter.py, tests/web_api/txt2img_test.py
Closes #2250 
just support for IP new model
tested with 1.1.416
=> Add support for IP Adapter Full Face

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
The control type selection feature has been around for a long while and many other code has been build on top of it, e.g. preset managements, etc.
#2136 is suspected to be caused by `ui_group.type_filter` being `None`.
This PR removes `controlnet_disable_control_type` option, and make control type selection always available.
=> :fire: Remove disable_control_type option

scripts/controlnet_ui/controlnet_ui_group.py, scripts/enums.py, scripts/global_state.py, tests/cn_script/global_state_test.py
Part of larger effort: https://github.com/Mikubill/sd-webui-controlnet/issues/2222.
This PR let `select_control_type` function only return ControlNet models that matches the currently active sd model's version. API endpoint `/controlnet/control_types`'s behaviour will not be affected.
TODO:
When user change SD model in A1111, trigger an update to module/models.
=> :sparkles: Filter cn model by sd version active

scripts/controlnet.py, scripts/enums.py, scripts/hook.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2222.
This PR adds a check on sd version conflict between ControlNet model and sd model. This can be useful for debugging purpose for API callers, as they do not have the auto model filtering in the UI.
Sample error message:
```shell
Exception: ControlNet model kohya_controllllite_xl_canny [2ed264be](StableDiffusionVersion.SDXL) is not compatible with sd model(StableDiffusionVersion.SD1x)
```
=> 🔊 Meaningful error message for sd version conflict

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
Closes #2262.
I believe the gradio version check there is no longer necessary as we now only target A1111 1.6.0+ users.
=> :fire: Remove gradio version check

README.md, javascript/active_units.js, javascript/openpose_editor.js, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/openpose_editor.py, style.css
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2236.
This PR adds an `upload JSON file` button when openpose control type is selected. This allows users directly use the JSON pose files they save, instead of going into the openpose editor and upload JSON there.
UI after change:
=> ✨Add JSON pose file upload button

annotator/anime_face_segment/LICENSE, annotator/anime_face_segment/__init__.py, scripts/global_state.py, scripts/processor.py
This PR lands #2212 on main. Dev is a temp branch right now. All PRs should target main.
=> Land #2212 on main

internal_controlnet/external_code.py, scripts/controlnet.py, scripts/controlnet_version.py, scripts/enums.py, scripts/hook.py
Since `sd-webui-controlnet` 1.1.420, users will be able to use image-wise controlnets. And, based on image-wise controlnets, the "StyleAlign" is avaliable.
[Style Aligned Image Generation via Shared Attention](https://style-aligned-gen.github.io/)
[Amir Hertz* 1](https://amirhertz.github.io/) [Andrey Voynov* 1](https://style-aligned-gen.github.io/) [Shlomi Fruchter† 1](https://style-aligned-gen.github.io/) [Daniel Cohen-Or† 1,2](https://danielcohenor.com/)
*1 Google Research 2 Tel Aviv University*
Previously, all ControlNet units will be applied to all images in your batch. Now, if you use “each ControlNet unit for each image in a batch”, you will have each ControlNet unit for each image in your batch.
For example, if your batch size is 4, then your 
ControlNet unit 0 will be applied to …
=> 1.1.420 Image-wise ControlNet and StyleAlign (Hertz et al.)

internal_controlnet/external_code.py, tests/web_api/txt2img_test.py
Previously we have switched `ControlNetUnit` to use `dataclass` decorator. This actually modifies the behaviour of the code, which no longer allow `ControlNetUnit` accept and ignore unrecognized params. Unrecognized params will cause exception and ControlNet not being applied.
This PR restores the original behaviour where unrecognized params from the API are ignored.
=> Ignore unrecognized ControlNetUnit params

internal_controlnet/external_code.py, scripts/controlnet.py, tests/web_api/txt2img_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2331.
This PR fixes the issue that `None` value not handled by `check_sd_version_compatible`. This PR also sets default value for ControlNetUnit.module and model to match the values used in the gradio UI.
=> :bug: Set default model/module to string values

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
Loopback option has no effect in non-batch generation. Hide the checkbox in non-batch tab so that it does not confuse users.
=> :art: Hide loopback checkbox in non-batch config

javascript/photopea.js, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/photopea.py, style.css
Closes #1736.
Provides better experience on https://github.com/Mikubill/sd-webui-controlnet/issues/2148.
How to use it during inpaint:
Task, generate a necklace on the girl's neck with a specific shape.
Step1: Draw inpaint mask.
Step2: Upload necklace image and preprocess with canny.
Step3: Click `Edit` on generated preprocessor image. A photopea editor modal will popup. The preprocessor image will be fetched from controlnet and paste in the editor automatically.
Step4: Align the position of the necklace canny edge map to desired location.
Step5: Click `Send to ControlNet` on the top left corner of the modal to update the canny edge map used by ControlNet.
Step6: Generate.
=> Quick edit of preprocessor result with photopea

scripts/controlnet.py
https://github.com/Mikubill/sd-webui-controlnet/issues/2371
User attempt to use revision on SD1.5 model, and confused that ControlNet does no effect. This PR explicitly raise an exception to notify user that revision is only compatible with SDXL base model.
=> :bug: Raise error when using revision on non-SDXL models

README.md, preload.py, scripts/controlnet.py
https://github.com/Mikubill/sd-webui-controlnet/issues/990
This PR adds support to log malloc memory usage breakdown on each generation. This feature is guarded behind commandline flag `--controlnet-tracemalloc`.
Sample output:
```
2023-12-30 22:26:26,381 - ControlNet - DEBUG - controlnet_main_entry ran in: 5.299 sec
2023-12-30 22:26:26,382 - ControlNet - INFO - After hook malloc:
2023-12-30 22:26:26,505 - ControlNet - INFO - D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py:460: size=1536 KiB (+1536 KiB), count=4 (+4), average=384 KiB
2023-12-30 22:26:26,506 - ControlNet - INFO - d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py:468: size=189 KiB (+189 KiB), count=995 (+995), average=195 B
2023-12-30 22:26:26,507 - ControlNet - INFO …
```
=> :loud_sound: Add tracemalloc to track memory usage

internal_controlnet/external_code.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/infotext.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2369.
This PR adds a new checkbox to control whether the ControlNet input image should be cropped to A1111 mask or not.
The checkbox is only visible if the user
- in img2img inpaint tab
- have inpaint area set to masked only
- check upload independent control image
=> :sparkles: Control inpaint crop per ControlNet unit

internal_controlnet/external_code.py, javascript/active_units.js, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/enums.py, scripts/hook.py, tests/web_api/txt2img_test.py
Closes #2378.
This PR removes global option `control_net_no_high_res_fix`, and adds the radio selection for hr option per ControlNet unit.
=> :sparkles: Add hr_option (Both, High res only, Low res only)

scripts/enums.py, scripts/hook.py
Closes #2381.
Replace 3.10 feature match statement with if/else blocks for backward compatibility.
=> :bug: Replace 3.10 match statement

javascript/openpose_editor.js, javascript/photopea.js, scripts/controlnet_ui/photopea.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2384.
This PR defers photopea iframe load to first click on `Edit`.
=> :wrench: Lazy load photopea editor

scripts/hook.py
Closes #2388.
Obviously `ControlParam` is referenced in other projects what we were not aware of.
=> :bug: Assign default value for hr_option

annotator/anime_face_segment/__init__.py
Fixes the following error when using `--use-cpu controlnet` or `--use-ipex` (where CUDA is not available):
```
Traceback (most recent call last):
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
output = await app.get_blocks().process_api(
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
result = await self.call_function(
File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
prediction = await anyio.to_thread.run_sync(
File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyn …
```
=> Fix anime_face_segment model load

.gitmodules, install.py, scripts/global_state.py, scripts/processor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2382.
Thanks [Fannovel16](https://github.com/Fannovel16) for his hard work extracting dependencies out for [hand refiner](https://github.com/wenquanlu/HandRefiner) in https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/src/controlnet_aux.
This PR adds a hand refiner portable submodule that does not need further build/instsall operations. This PR is the first step as discussed in #2382: Adding `depth_hand_refiner` to preprocessor list.
Now you can manually draw the inpaint mask on hands and use a depth ControlNet unit to fix hands with following steps:
TODOs:
=> :sparkles: Hand refiner preprocessor

scripts/controlnet_ui/controlnet_ui_group.py
Closes #2402.
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2403.
This PR makes `Crop input image based on A1111 mask` checkbox show regardless of `Use independent control image` checkbox's state.
This PR also makes the checkbox checked by default, which performs the crop by default (Original behaviour).
=> :wrench: Fix crop input image checkbox visibility

javascript/active_units.js
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2390.
Before A1111 1.7.0 `#txt2img_hr-visible-checkbox` element does not exist, which will cause UI to be stuck in that JS register observer loop.
This PR fixes the issue for A1111 < 1.7.0.
=> :bug: Backward compatible with A1111 1< 1.7.0

install.py
User has reported that `subprocess.run(["git", "submodule", "init"], check=True, cwd=repo_root)` throws exception but manually run the command works.
=> :bug: Handle git submodule command exception

javascript/photopea.js
As requested by @w-e-w, I made disabling the feature easier. Now click cancel will automatically check the checkbox in settings tab, and hide all edit buttons in current session.
=> :wrench: Auto disable photopea edit on confirm alert cancel

javascript/photopea.js, scripts/controlnet.py
@huchenlei see how you like this approach, feel free to make modifications
---
add a new setting `Photopea popup warning` this controls if you pop up is shown before reuning photopea, default enabled
provides a middle ground for users that may wish to use photpea form time to time doesn't want to accidentally use it
>sadly no multi-user diffrent config support
when `Photopea popup warning` is enable
pop up will be shown on the first time that a user tries to use photopea
if the user choose cancel nothing happens..... well it cancels and nothing else happes
if the user clicks on the photopea again the cycle repeats
if the user choose OK photopea is loaded
the value is set so that the pop-up doesn't show up again for for THIS browser session (until the page reloads)
---
if the user disables …
=> alternative photopea popup warning

install.py
Closes #2427.
The root cause might be git not finding the submodule script location:
https://stackoverflow.com/questions/54672008/submodule-appears-to-be-a-git-command-but-we-were-not-able-to-execute-it.
Since A1111 has GitPython dependency, this PR makes use of that instead of raw subprocess call on git. This hopefully resolves the issue.
Also even when submodule fail to sync, the extension should still be able to load now.
=> :bug: Try fix submodule command not found

README.md
README.md was pointing to location of old notebook style example file for the api examples which no longer exist. Updated link to location of the .py example currently present
=> Update api example in README.md

install.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2445.
Previously insightface lib is installed in global python env. This PR fixes that.
=> :bug: Fix install script

scripts/controlmodel_ipadapter.py, scripts/controlnet_model_guess.py
Users have reported that faceid v2 is broken. The PR fixes the implementation. You should see log
`ControlNet - INFO - IP-Adapter faceid plus v2 detected.` when you use v2 model.
=> :bug: Fix IP-Adapter face id plus v2

scripts/processor.py
`ip-adapter_clip_sdxl_plus_vith` also does not utilize `control mode`. Hide control mode selection for it as well.
=> :bug: Hide control mode for ip-adapter_clip_sdxl_plus_vith

annotator/densepose/__init__.py, annotator/densepose/densepose.py, scripts/global_state.py, scripts/processor.py
Reverts Mikubill/sd-webui-controlnet#2457
=> Reland "Add Densepose (TorchScript)"

scripts/controlnet.py
This PR changes the if guards on getting A1111 img2img mask to assert guards.
Reasons:
- Without interference, mask from A1111 is always a 2D np array. If other extensions breaks this invariant, instead of dropping the mask, we fail explicitly now.
- Mask shape agreeing witht input shape is guranteed if using inpaint tab.
- If mask of incorrect size is uploaded using either API or inpaint upload tab, A1111 will report error.
I have tested following scenarios:
- Inpaint via API
- Inpaint in GUI (Inpaint tab)
- Inpaint in GUI (Inpaint upload)
=> :hammer: Change if to assert on mask invariants

scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2469.
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2245.
Previously, it was assumed that model only contains state_dict loaded from model file. However, ip-adapter models also contain input image embedding, weight, and many other values, so ip-adapter models should not be cached.
This is a dirty fix. Later we should have a flag on model object specifying whether the model should be cached or not.
After the fix with example inputs used in #2469:
2 ipadapter units:
1girl (weight = 0.2)
tiger (weight = 0.5)
=> :bug: Uncache ip-adapter models

annotator/clipvision/__init__.py
In the inference service using ControlNet, I observed a significant increase in time consumption when utilizing clip vision-related preprocessors (e.g. `adapter_clip_sd15`). The time fluctuates between 8s and 250s, depending on machine load. The typical time is around 10s. My machine is equipped with an A10 GPU, 96C CPU, and 251GB memory.
Upon investigation, I found a substantial portion of the time is spent in the following section: https://github.com/Mikubill/sd-webui-controlnet/blob/main/annotator/clipvision/init.py#L101.
Further exploration revealed that these time-consuming operations are primarily due to extensive initialization, such as:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py#L333-L334 …
=> feat: significantly optimize the time consumption of clip vision

scripts/controlnet.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2480.
That check for mask probably need to be after outpaint expanded the canvas. For now, I will just remove the check.
=> :bug: Fix outpaint

scripts/controlnet.py, tests/web_api/full_coverage/inpaint_test.py
Closes #2484.
Added dedicates unittests for no-mask outpainting scenario, so the feature break will be prevented in the future.
=> :bug: Fix outpaint 2

scripts/controlnet.py, scripts/enums.py
Closes #2487.
This PR allows SD1x and SD2x to be treated as compatible.
=> :wrench: Loosen is_compatible SD version check

annotator/clipvision/__init__.py, scripts/api.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/processor.py
Users with limited vram have reported issue running CLIP preprocessor alongside with ControlNet (https://github.com/Mikubill/sd-webui-controlnet/discussions/2472#discussioncomment-8165388). This PR offers the option to let users load/run CLIP preprocessor model on CPU.
=> :wrench: Add option to run CLIP preprocessor on CPU

.gitmodules, install.py, requirements.txt, scripts/processor.py
After https://github.com/huchenlei/HandRefinerPortable/pull/2 is merged (making that repository Pip installable), this PR changes sd-webui-controlnet to not use a Git submodule for it anymore.
This was discussed with @w-e-w and @huchenlei on the A1111 discord.
This will not clean up any previously cloned submodule (nor deinit submodules), though.
Because we have removed submodule `hand_refiner_portable`, there should no longer be any issue of renaming dir. We suspect previously it was `git submodule update` holding some resources, which cause `os.rename` to fail with PermissionError.
- Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2482
- Closes https://github.com/Mikubill/sd-webui-controlnet/discussions/2488
=> Use pip for HandRefinerPortable

.gitignore, install.py
This PR removes submodule `hand_refiner_portable` completely.
This PR also prevents reinstalling pip package `handrefinerportable` on every A1111 startup.
=> :fire: Remove hand_refiner_portable submodule

install.py, requirements.txt
Closes #2501.
This PR make handrefiner install directly from a prebuild wheel, so that users don't need to install extra dependencies.
=> :wrench: Install handrefiner from prebuild wheel

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2494.
Closes #2270.
This PR adds the callback when sd checkpoint config. When it changes, model choices will be updated to match the current sd version.
This PR also does a large refactoring to delay register of callbacks after all A1111 component that we use/care have been initialized.
Local testing has verified that following features are still are working:
=> Update model dropdown choices when sd checkpoint change

scripts/controlnet_ui/controlnet_ui_group.py
Closes #2520.
Only update controlnet model when necessary (sd model's version changed).
=> :bug: Only update model when necessary

scripts/batch_hijack.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/enums.py, scripts/utils.py
Related discussion: https://github.com/Mikubill/sd-webui-controlnet/issues/2478#issuecomment-1894173725.
User has requested that we provide a way to easily input the whole directory of images into a unit. This PR partially does that by providing the `Multi-Inputs` tab.
Now you can specify a directory with N images. N ControlNet units will be added on generation each unit accepting 1 image from the dir. This is also the prework of implementing IPAdapter portrait: https://github.com/tencent-ailab/IP-Adapter/commit/2397f7c3735c89cd2c9da3229d95d99673f36464.
=> :sparkles: Support multi-inputs

internal_controlnet/external_code.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py
=> :art: Multi-Inputs more user friendly UI

internal_controlnet/external_code.py, scripts/controlnet.py, tests/web_api/full_coverage/inpaint_test.py
This PR moves inpaint crop logic out of `controlnet_main_entry`.
=> :truck: Move inpaint crop logic as a function

scripts/controlnet.py, scripts/controlnet_model_guess.py
This PR integrates model type detection into model detection, so that we don't need to do extra detecting logic in `controlnet_main_entry`.
=> :truck: Integrate model type detection into model detection

scripts/controlnet.py
Moves `control_mode` to a closer location where it is used.
=> :truck: Move control_mode

internal_controlnet/external_code.py, scripts/controlmodel_ipadapter.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/global_state.py, scripts/processor.py, scripts/utils.py, tests/web_api/full_coverage/ipadapter_test.py
Previous multi-inputs support https://github.com/Mikubill/sd-webui-controlnet/pull/2525 essentially unfolds the multi-input unit into multiple units, and do processing, which is not very efficient.
This PR implements the real multi-inputs ControlNet unit, which allow multiple input images to be passed together to FaceID preprocessor in one pass.
In API, a new syntax is introduced to support this. The simple list syntax has been taken (first item image, second item mask), so we have to do extra workaround.
```python
{"image": [{"image": img} for img in imgs]}
```
faceid portrait multiple units
faceid portrait single unit multiple inputs
There are some slight differences. This can be attributed to floating point calculation loss. I think the performance is equivalent. Please file an issue …
=> Real multi-inputs ControlNet unit

scripts/global_state.py
Mainly for IPAdapter preprocessors as they are sensible to SD version.
=> :wrench: Filter preprocessor selection based on sd version

scripts/controlnet.py, scripts/global_state.py
Related issue: https://github.com/Mikubill/sd-webui-controlnet/issues/2546
Many users have difficulties interpret error on wrong preprocessor/model pair. This PR makes error log more explicit.
Sample output:
```
2024-01-22 19:22:30,880 - ControlNet - ERROR - Invalid pair of IP-Adapter preprocessor(ip-adapter_clip_sd15) and model(ip-adapter-faceid-plus_sd15 [d86a490f]).
{
"ip-adapter_clip_sdxl": lambda model: "faceid" not in model and "vit" not in model,
"ip-adapter_clip_sdxl_plus_vith": lambda model: "faceid" not in model and "vit" in model,
"ip-adapter_clip_sd15": lambda model: "faceid" not in model,
"ip-adapter_face_id": lambda model: "faceid" in model and "plus" not in model,
"ip-adapter_face_id_plus": lambda model: "faceid" in model and "plus" in model,
}
```
=> :wrench: Explicit error on ipadapter invalid preprocessor/model pair

scripts/controlmodel_ipadapter.py, scripts/controlnet.py, scripts/enums.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2579.
Controlllite also have same issue that it cannot be cached, because model object contains input image information. To make things worse, Controlllite has image information stored at lowest level nn.Module, so major change is needed. Filed #2585 for tracking.
=> 🐛 Properly cache ip-adapter models

internal_controlnet/external_code.py, scripts/controlmodel_ipadapter.py, scripts/controlnet.py, scripts/hook.py, scripts/processor.py, tests/web_api/full_coverage/ipadapter_test.py, tests/web_api/full_coverage/template.py
Relands https://github.com/Mikubill/sd-webui-controlnet/pull/2578.
With multiple inputs, the projected embedding for all inputs are averaged. This causes slight generation difference comparing to the current multi-units approach, because of floating point precision.
Current multi-unit approach:
Real multi-inputs apparoch:
You can observe some subtle difference here and there, but overall image quality is preserved. You can still use the multi-unit approach in the API as demonstrated in tests.
=> :zap: Real multi-inputs for all IP-Adapters

scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/vladmandic/automatic/issues/2760.
SDNext users have reported that ControlNet UI callbacks are not registered. After some investigation, we found that `setting_sd_model_checkpoint` is not available in SDNext. This PR disabled callback currently bind on `setting_sd_model_checkpoint` until we find a good way to register callbacks after all gradio components are ready in A1111. Currently `modules/script_callbacks.py` does not provide such hook. There is a "on_before_ui" but no "on_after_ui" now.
=> :bug: Disable checkpoint callback for SDNext

scripts/controlnet_ui/controlnet_ui_group.py
Reverts Mikubill/sd-webui-controlnet#2595
Reason: Broken img2img independent image upload.
=> Revert ":bug: Disable checkpoint callback for SDNext"

scripts/controlnet.py
Context: https://github.com/Mikubill/sd-webui-controlnet/discussions/2589#discussioncomment-8273701.
Now we have instant id, which always use 2 models at the same time. It is reasonable to to increase the default model cache size to 2, because cache size = 1 means loading model on each generation for instant id.
=> :wrench: Increase default model cache size to 2

scripts/controlnet.py
https://github.com/Mikubill/sd-webui-controlnet/issues/2603.
User named model file wrong, and was confused. This PR adds detected model type to the log, so that the error becomes more obvious.
=> :load_sound: Print control_model_type when loading model

scripts/processor.py
`i` is no longer defined in the scope.
=> :bug: Fix error message

example/advanced_weighting_example/api_advanced_weighting.py, example/chatgpt.py, example/inpaint_example/api_inpaint.py, example/txt2img_example/api_txt2img.py
Using PIL to save images re-encodes them, losing metadata and potentially quality (if using lossy compression like JPEG). This way, images are saved as-is, and are identical to those saved by webui.
The wiki page should probably be updated as well.
Example:
_(Open in PNG Info)_
| Before | After |
|--------|--------|
| ![img2img-0](https://github.com/Mikubill/sd-webui-controlnet/assets/4073789/f9ed721e-df8a-416f-9711-b3260f1acd18) | ![img2img-0](https://github.com/Mikubill/sd-webui-controlnet/assets/4073789/012686a6-a7fa-45e7-ac60-651fd818c7ad) |
=> Correct image saving in API examples

annotator/clipvision/__init__.py, scripts/global_state.py
Fixed 2 minor compatibility issues preventing ControlNet from working in WebUI versions >= 1.3.0 and < 1.5.0.
=> Compatibility fixes for WebUI < v1.5.0

annotator/zoe/zoedepth/models/base_models/midas.py, annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/beit.py
This issue still occurs in pytorch 2.1.2. As a library with such a broad user base, if the cost is not too high, I think we should consider compatibility issues to ensure that our users do not feel lost when encountering these errors.
#2113
=> type error in depth zoe, converting numpy type into int

scripts/controlnet_ui/controlnet_ui_group.py
Added fallback detection of component "txt2img_hr-checkbox" for WebUI versions < 1.6.0.
=> Compatibility fix for WebUI < v1.6.0

scripts/batch_hijack.py, scripts/controlmodel_ipadapter.py, scripts/controlnet.py, scripts/controlnet_model_guess.py, scripts/controlnet_sparsectrl.py, scripts/controlnet_version.py, scripts/enums.py, scripts/global_state.py, scripts/hook.py, scripts/processor.py
Given that huchenlei has implemented multi-image upload, I don't have to make too much change to the code now.
New features will only include SparseCtrl. Magic Animate and all other new works that include reference models will be forge only.
We potentially can and need to re-write this extension in a way similar to forge so that we can make maintenance easier.
#2352 will be abandoned. I expect to merge this PR in this week.
=> AnimateDiff 2.0.0-a ControlNet part

scripts/controlnet_ui/controlnet_ui_group.py
Closes #2623. Gradio4 removes `IOComponent` from `gr.components` namespace.
=> Rename IOComponent to Component for Gradio4

annotator/clipvision/__init__.py, annotator/lama/saicinpainting/training/losses/segmentation.py, annotator/zoe/zoedepth/models/base_models/midas_repo/run.py
Relands https://github.com/Mikubill/sd-webui-controlnet/pull/2503.
As discussed in https://github.com/Mikubill/sd-webui-controlnet/pull/2508#issuecomment-1993887097, we should use `devices.get_device_for("controlnet")` to get device if cuda is available so that environment with multiple cuda instances can better utilize the GPU power with multiple A1111 instances running.
The reland will not cause AMD/Intel card to fail as now they will fall back to cpu if cuda is not available.
=> Fix device for multi-gpu env

scripts/controlnet.py, scripts/global_state.py, scripts/ipadapter/presets.py, scripts/processor.py
Closes #2643.
This PR adds `ip-adapter-auto` meta preprocessor that automatically selects the correct preprocessor based on ipadapter model used.
Note: The preprocessor selection is based on model file name. So please keep the model file name as the same in official huggingface ipadapter repo.
You should see following log line in your console:
`2024-03-29 23:09:19,001 - ControlNet - INFO - ip-adapter-auto => ip-adapter_clip_g`
This PR is also part of https://github.com/Mikubill/sd-webui-controlnet/issues/2700.
=> Unify IP-Adapter preprocessor

.github/workflows/tests.yml, .gitignore, tests/conftest.py, tests/web_api/detect_test.py, tests/web_api/template.py
This PR migrates `tests/web_api/detect_test.py` to new API template, and expand coverage to all preprocessors in local run.
To run `detect_test.py` locally, run command 
```
python -m pytest -vv --junitxml=test/results.xml --cov .\extensions\sd-webui-controlnet\ --cov-report=xml --verify-base-url .\extensions\sd-webui-controlnet\tests\web_api\detect_test.py
```
=> Migrate detect_test and improve coverage

requirements.txt, tests/web_api/detect_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2693.
Upstream A1111 change probably dropped `addict` and `yapf` in 1.8.0, so we need to manually include them here.
=> Fix seg preprocessor

internal_controlnet/external_code.py, scripts/animate_diff/batch.py, scripts/controlnet.py
This PR does following 2 refactors:
- Add `is_animate_diff_batch` property on `ControlNetUnit`
- Move animate diff's batch input processing out of `choose_input_image`
=> Move ad batch input

annotator/clipvision/__init__.py, internal_controlnet/external_code.py, scripts/controlnet.py, scripts/processor.py, tests/web_api/clip_mask_test.py
This PR is part of https://github.com/Mikubill/sd-webui-controlnet/issues/2700.
This PR implements CLIP mask. Now ip-adapter non-faceid models can accept mask to ignore part of image.
Here is an example:
Infotext
```
skull sheild, absurdres, highres, (masterpiece:1.2), (best quality, highest quality),
Negative prompt: (lowres, low quality, worst quality:1.2), (text:1.2), watermark, (frame:1.2), deformed, ugly, deformed eyes, blur, out of focus, blurry, deformed cat, deformed, photo, anthropomorphic cat, monochrome, photo, pet collar, gun, weapon, blue, 3d, drones, drone, buildings in background, green
Steps: 20, Sampler: DPM++ 2M, Schedule type: Karras, CFG scale: 7, Seed: 1714864127, Size: 512x512, Model hash: b42b09ff12, Model: cetusMix_v4, Clip skip: 2, ControlNet 0: "Module: …
```
=> Add clip mask support

scripts/ipadapter/ipadapter_model.py, scripts/ipadapter/plugable_ipadapter.py
This PR removes `ImageEmbed.bypass_average` as it is never written to.
The field was introduced in https://github.com/Mikubill/sd-webui-controlnet/pull/2661
sd-webui-animatediff also does not write to this field: https://github.com/search?q=repo%3Acontinue-revolution%2Fsd-webui-animatediff%20bypass_average&type=code
The implementation to bypass average is also incorrect as it also bypasses ipadapter's projections.
=> Remove unused field bypass_average

scripts/processor.py
This PR makes `ip-adapter_face_id*` preprocessors pick largest face detected instead of first face detected. This is the same behaviour in instantid preprocessor.
This change is helps user get more control on preprocessor result, as how insightface decides which face is the first face is not very clear to the user.
=> Make ip-adapter face_id pick largest face instead of first face

internal_controlnet/external_code.py, scripts/api.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, tests/web_api/detect_test.py, tests/web_api/ipadapter_clip_api.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2283.
This PR allows user save CLIP output by calling `controlnet/detect` API, and use them in API payload.
Detect Payload example in tests/web_api/ipadapter_clip_api.py:
```python
def test_ipadapter_clip_api():
"""Use previously saved CLIP output in ipadapter run."""
resp = detect_template(
dict(
controlnet_input_images=[realistic_girl_face_img],
controlnet_module="ip-adapter_clip_h",
)
)
ipadapter_input = resp["tensor"]
APITestTemplate(
"test_ipadapter_clip_api",
"txt2img",
payload_overrides={},
unit_overrides={
"ipadapter_input": ipadapter_input,
"model": get_model("ip-adapter_sd15"),
},
).exec()
```
=> :sparkles: Save/Use CLIP output in API

install.py, requirements.txt
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15556
First critical installation issue
`insightface` specifies `any` version of `albumentations`
and so will pip will install the newest version of `albumentations`
`albumentations` had an update `1.4.4` in the past 24 hr see [pypi/albumentations/history](https://pypi.org/project/albumentations/#history) 
it introduces a new requirement
- pydantic required: >=2.6.4
webui 1.9 with gradio==3.41.2 / fastapi==0.94.0 requires
- pydantic required: >=1.7.4,<3.0.0,!=2.0.1,!=2.0.0,!=1.8.1,!=1.8
webui 1.9 is not compatible with `pydantic>=2.0`
which causes web UI to not launch
- I believe this will change when we update to https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14184
solution for now
in controlnet
pin …
=> Install fix, albumentations pydantic insightface, onnxruntime-gpu

scripts/ipadapter/presets.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2777.
This PR adds ipadapter composition models to presets so that `ip-adapter-auto` preprocessor can detect them.
=> Add ipadapter composition presets

scripts/ipadapter/presets.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2786.
I am not sure why we have both `ip-adapter-plus_sd15` and `ip-adapter_sd15_plus`. I also have `ip-adapter_sd15_plus` downloaded in my models directory, but it is not in the official repo: https://huggingface.co/h94/IP-Adapter/tree/main/models.
Guess I will add it anyway since some people get this model name from legacy downloads.
=> Add preset ip-adapter_sd15_plus

scripts/preprocessor/legacy/preprocessor_compiled.py, scripts/preprocessor/model_free_preprocessors.py, scripts/supported_preprocessor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2798
This PR does following tasks:
- Merge "blur" control type into "tile"
- Merge "sketch" control type into "scribble"
- Add "instructp2p" control type to "none" preprocessor
=> Restore various control type changes

tests/web_api/detect_test.py
CLIP preprocessor was supported in `controlnet/detect` endpoint in https://github.com/Mikubill/sd-webui-controlnet/pull/2721.
This PR fixes detect endpoint test to handle CLIP preprocessors.
=> Fix detect test for non-image return values

internal_controlnet/external_code.py, scripts/api.py, scripts/controlnet.py, scripts/preprocessor/ip_adapter_auto.py, scripts/preprocessor/lama_inpaint.py, scripts/preprocessor/legacy/legacy_preprocessors.py, scripts/preprocessor/normal_dsine.py, scripts/supported_preprocessor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2800.
Preprocessor model unload behaviour changed in https://github.com/Mikubill/sd-webui-controlnet/pull/2754 to align with SD forge's impl. Forge does eager unload, which is not ideal for CLIP, which takes very long to load/unload. This PR restores the original behaviour which keeps active preprocessors between runs.
=> Keep active preprocessor models

scripts/controlnet.py, scripts/enums.py, scripts/hook.py, tests/web_api/effective_region_test.py, tests/web_api/template.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2451.
Currently only API support. GUI support will come later.
Previously effective_region_mask support was added to ipadapter in https://github.com/Mikubill/sd-webui-controlnet/pull/2785. Now it is added to ControlNet/T2IAdapter as well.
Example on depth control:
Input image:
Mask image:
Output image:
You can observe that only the left part of the generation got guided by the depth map.
=> Add effective_region_mask for ControlNet [API]

scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2829.
This PR replaces mask upload with effective region mask.
=> Replace mask upload with effective region mask

internal_controlnet/external_code.py, requirements.txt, scripts/api.py, scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/enums.py, scripts/ipadapter/image_proj_models.py, scripts/ipadapter/ipadapter_model.py, scripts/ipadapter/plugable_ipadapter.py, scripts/ipadapter/presets.py, scripts/ipadapter/pulid_attn.py, scripts/preprocessor/__init__.py, scripts/preprocessor/inpaint.py, scripts/preprocessor/lama_inpaint.py, scripts/preprocessor/legacy/legacy_preprocessors.py, scripts/preprocessor/pulid.py, scripts/supported_preprocessor.py, scripts/utils.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2835.
[PuLID](https://github.com/ToTheBeginning/PuLID) is an ip-adapter alike method to restore facial identity. It uses both insightface embedding and CLIP embedding similar to what ip-adapter faceid plus model does. However, there is an extra process of masking out the face from background environment using facexlib before passing image to CLIP. PuLID also uses Eva CLIP instead of normal CLIP. In the attn overrides, PuLID also does something more than IPAdapter, as it zero pads the tensor and adds to ortho of hidden states. If you are interested you can read their paper on how this is handled.
PuLID uses both evaclip embedding and insightface embedding as proj module input. So in order to use the feature, you need to install …
=> Support PuLID

scripts/controlnet.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/controlnet_ui/preset.py, scripts/infotext.py, tests/cn_script/batch_hijack_test.py, tests/cn_script/cn_script_test.py, tests/external_code_api/external_code_test.py, tests/external_code_api/script_args_test.py
This PR drops "external_code." prefix for ControlNetUnit. Now the name is directly imported to cause less distraction on code length.
=> Drop external_code. prefix

internal_controlnet/args.py, unit_tests/args_test.py
=> Fix ControlNetUnit legacy field alias

internal_controlnet/args.py, unit_tests/args_test.py
=> Fix resize mode enum values for deforum

internal_controlnet/args.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2863.
=> Add ControlNetUnit.batch_mask_dir for compatibility

scripts/controlnet_ui/controlnet_ui_group.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2872
Previously effective region mask upload is only displayed in single image input tab. This PR makes it display regardless of input tab type.
=> Display effection region mask upload regardless of input mode

scripts/supported_preprocessor.py
https://github.com/Mikubill/sd-webui-controlnet/issues/2862
Temporarily disable buggy unload logic for PuLID, so that no VRAM leak happens. It is at least better to just keep the preprocessor models in VRAM instead of trying to unload them and cause VRAM leak.
=> Prevent PuLID preprocessor unload. Temp Fix VRAM leak.

scripts/controlnet.py
If Hires fix is enabled, controlnet inpu image will always be cropped since Hires fix's script name is `Hires Upscale(r)`.
This causes issues with some extensions like ADetailer. 
One case is when using IP-Adapter FaceID with ADetailer, the input face image will be cropped, and Insightface will fail to detect faces in the cropped image.
This pull request fixes this issue.
For future improvement, I suggest that a new argument (e.g. `is_cropping_disabled` with default value `False`) should be added to allow third-party extension to disable this cropping feature.
=> Fix upscale script checking

tests/web_api/modules_test.py
`te_hed` alias will no longer be supported.
=> Fix test expectation

scripts/controlnet.py
Closes #2886.
The root cause of this issue is that both img2img script instance and txt2img script instance has access to the same group of enabled_units objects, and each batch iteration, `batch_tab_process_each` on both img2img script and txt2img script are invoked to advance the iterator on the same unit.
Previously units are copied on each call to `Script.get_enabled_units`, which is costly, but maintains the correctness. This PR solves the issue by distinguish txt2img and img2img script, which resolves the issue more fundamentally, and also avoiding copy cost of ControlNetUnit.
=> Fix ControlNet batch

internal_controlnet/args.py, unit_tests/args_test.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2871.
Pydantic BaseModel does not copy correctly when using python stdlib's `copy.copy` to perform shallow copy by default. This PR fixes that.
=> Fix ControlNetUnit copy issue

internal_controlnet/args.py, scripts/controlnet_ui/controlnet_ui_group.py, tests/web_api/detect_test.py, tests/web_api/generation_test.py
Previous PR https://github.com/Mikubill/sd-webui-controlnet/pull/2847 set the default value to `False`. However I noticed that some extensions are relying on the default True value of ControlNetUnit.enabled.
This PR restore the old behaviour.
=> Set default value of ControlNetUnit.enabled to True

internal_controlnet/args.py, scripts/controlnet_ui/controlnet_ui_group.py, tests/web_api/detect_test.py, tests/web_api/generation_test.py
Reverts Mikubill/sd-webui-controlnet#2912
=> Revert "Set default value of ControlNetUnit.enabled to True"

requirements.txt
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2608.
According to https://github.com/Mikubill/sd-webui-controlnet/issues/2608#issuecomment-2125418379, timm 0.9.5 is the last good version that runs depth_zoe without problem.
=> Fix depth_zoe

internal_controlnet/args.py
Using `= []` in pydantic BaseModel will make all instances share the same default object, which is dangerous.
=> Fix args initializer

install.py
When starting the Web UI, the `install.py` script reads `requirements.txt`. If a package version uses ">", it is treated as a redirection in `pip install`, creating an unintended file.
Running `webui.bat` or `webui.sh` creates a file named "=4.8.0" due to "opencv-python>=4.8.0" in `requirements.txt` being misinterpreted.
I enclosed the package and version specification in double quotes in `install.py`.
=> Fix issue with > in pip cmd causing file creation

requirements.txt
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2967.
User reported issue with pydantic 2.0+ installed. This PR explicitly adds the pydantic dependency.
=> Add pydantic dep

internal_controlnet/args.py, scripts/cldm.py, scripts/controlnet.py, scripts/controlnet_core/controlnet_union.py, scripts/controlnet_model_guess.py, scripts/controlnet_ui/controlnet_ui_group.py, scripts/enums.py, scripts/hook.py, scripts/supported_preprocessor.py
Closes https://github.com/Mikubill/sd-webui-controlnet/issues/2986
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0
Do not use key map with face and hand as the union controlnet does not seem to be trained with hand/face annotation
Note: `ofade20k` preprocessor does not seem to work
Currently the multi-controlnet is not working in the optimal way described in the original paper, but you can still try use it, as it can help you save VRAM by avoid loading another controlnet for different type of control.
Input images
Mask
Generation parameters (Parameters including seed are fixed for all examples)
```
1girl, sitting on throne,, absurdres, highres, (masterpiece:1.2), (best quality, highest quality),
Negative prompt: (lowres, low quality, worst quality:1.2), (text:1.2), watermark, …
```
=> Support union ControlNet

scripts/cldm.py, scripts/controlnet_model_guess.py, scripts/enums.py
The promax union model supports 2 new control types: Tile and Inpaint. You can download the model here: https://huggingface.co/xinsir/controlnet-union-sdxl-1.0/tree/main
```
1girl, hatsune miku,, absurdres, highres, (masterpiece:1.2), (best quality, highest quality),
Negative prompt: (lowres, low quality, worst quality:1.2), (text:1.2), watermark, (frame:1.2), deformed, ugly, deformed eyes, blur, out of focus, blurry, deformed cat, deformed, photo, anthropomorphic cat, monochrome, photo, pet collar, gun, weapon, blue, 3d, drones, drone, buildings in background, green
Steps: 30, Sampler: DPM++ 2M, Schedule type: Karras, CFG scale: 7, Seed: 3582562933, Size: 768x1024, Model hash: 5a268fde84, Model: netaArtXL_v10, Clip skip: 2, ControlNet 0: "Module: blur_gaussian, Model: …
```
=> Support ProMax union model

install.py
recently on every launch install.py the message keep poping up on launch
```
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
```
this is due to improper version comparison in `install.py`
`comparable_version()` in `install.py` retruns `Tuple of strings`
https://github.com/Mikubill/sd-webui-controlnet/blob/b63899a654ee2f70d475c259691f35ac67c320d4/install.py#L15-L16
until recently directly comparing `Tuple of strings` work good enough but opencv-python updated to vesrion `4.10.x.x`
when checking for [`opencv-python>=4.8.0`](https://github.com/Mikubill/sd-webui-controlnet/blob/b63899a654ee2f70d475c259691f35ac67c320d4/requirements.txt#L3)
the `Tuple of strings` `('4', '10', '0', '84')` >= `('4', '8', '0')` this retruns `False`
due to the …
=> fix version parsing
